*****************************************************************************************************************
**Variable labelling
*****************************************************************************************************************
*******Student Survey Literacy
lab var  interview_date"Date of Interview"
lab var  start_time"Interview start time"
lab var  SUP_NAME"Supervisor name"
lab var end_time"Interview End time"
lab var ENUM_NAME"Enumerator name"
lab var tabletUserName"Tablet registered user"
lab var  status"Student status"
lab var consent"Do you have any questions? Are you ready to begin?"
lab var  survey_language"Which language are you currently interviewing in?"
lab var  reading_comprehension_q1"What day do they have fun? [Dimaas]"
lab var  reading_comprehension_q2"Where are Ali and his little brother? [at school, etc] "
lab var  reading_comprehension_q3"What does Sidi bring with him? [a ball] "
lab var  reading_comprehension_q4"Who plays ball? [Ali; Sidi; his brother; Ali and Sidi; etc.] "
lab var  reading_comprehension_q5"How are the children at the end of Game? [happy] "
lab var  reading_comprehension_q6"Why are they happy? [they have played well; etc.] "
lab var  correct_number_grid_1"Enumerator: Number of corrects in the number grid 1"
lab var  correct_number_grid_2"Enumerator: Number of corrects in the number grid 2"
lab var  correct_dd_grid_1"Enumerator: Number of corrects in the digital discrimination 1"
lab var  correct_dd_grid_2"Enumerator: Number of corrects in the digital discrimination 2"
lab var  correct_addition_grid_1"Enumerator: Number of corrects in addition grid 1"
lab var  correct_addition_grid_2"Enumerator: Number of corrects in addition grid 2"
lab var  addition_strategy"Note the strategy the child used to answer the question (more than one option can be chosen):"
lab var  correct_substraction_grid_1"Enumerator: Number of corrects in substraction grid 1"
lab var  correct_substraction_grid_2"Enumerator: Number of corrects in substraction grid 2"
lab var  substraction_strategy"Note the strategy the child used to solve the question (more than one option can be chosen):"
lab var  Gender"Gender of child: "
lab var  Age"How old are you ?"
lab var  Grade"What grade are you in now?"
lab var  B4"Did you attend a preschool program before Grade 1/CI?"
lab var  B5"What language(s) do you speak at home?"
lab var  B5_s1"Please specify - 1"
lab var  B5_s2"Please specify - 2"
lab var  B5_s3"Please specify - 3"
lab var  B6"What language(s) do you speak while playing with your friends?"
lab var  B6_s1"Please specify 1"
lab var  B6_s2"Please specify 2"
lab var  B6_s3"Please specify 3"
lab var  B7"During the last full week of school, how many days did you miss?"
lab var  B8"Have you eaten today?"
lab var  B9"Does your family have electricity at home?"
lab var B10"At home, do you or anyone else in your household have:"
lab var  B10a"Television"
lab var  B10b"Radio"
lab var  B10c"Computer/Laptop"
lab var  B10d"Motorcycle"
lab var  B10e"Car or truck"
lab var  B10f"Mobile phone"
lab var  B10g"Fridge"
lab var  B10h"Microwave"
lab var  B10j"Washing machine"
lab var  B11"Do you have any reading material at home?  "
lab var  B12"Does anyone help you with your homework? "
lab var  B13"During the long school break (summer), did you receive any summer classes at your school, at another school, in your neighbourhood, or at your house?"
lab var  B14"14.	Were the summer classes part of Ndaw Wune Vacances 2025?"
lab var  ENUM_COMMENTS"Enumerator additional comments"

lab var addition_grid_1_1"a. 1+3=4"
lab var addition_grid_1_2"b. 2+7=9"
lab var addition_grid_1_3"c. 4+5=9"
lab var addition_grid_1_4"d. 3+3=6"
lab var addition_grid_1num_corr"Number of items correct"
lab var addition_grid_2_1"a. 13+6=19"
lab var addition_grid_2_2"b. 12+24=36"
lab var addition_grid_2_3"c. 14+9=23"
lab var addition_grid_2_4"d. 23+62=85"
lab var addition_grid_2num_corr"Number of items correct"
lab var addition_grid_3_1"a. 143+76=219"
lab var addition_grid_3_2"b. 259+463=722"
lab var addition_grid_3_3"c. 617+162=779"
lab var addition_grid_3_4"d. 361+187=548"
lab var addition_grid_3num_corr"Number of items correct"
lab var addition_strategy_1"Finger marks/ticks"
lab var addition_strategy_2"Paper and pencil"
lab var addition_strategy_3"Mental arithmetic"
lab var correct_addition_grid_1"Enumerator: Number of corrects in addition grid 1"
lab var correct_addition_grid_2"Enumerator: Number of corrects in addition grid 2"

lab var substraction_grid_1_1"a. 4–3=1"
lab var substraction_grid_1_2"b. 9–7=2"
lab var substraction_grid_1_3"c. 6–3=3"
lab var substraction_grid_1_4"d. 8–1=7"
lab var substraction_grid_1num_corr"Number of items correct"
lab var substraction_grid_2_1"a. 19–6=13"
lab var substraction_grid_2_2"b. 25–7=18"
lab var substraction_grid_2_3"c. 26–14=14"
lab var substraction_grid_2_4"d. 64–32=32"
lab var substraction_grid_2num_corr"Number of items correct"
lab var substraction_grid_3_1"1. 176–132=44"
lab var substraction_grid_3_2"2. 512–311=201"
lab var substraction_grid_3_3"3. 649-431=118"
lab var substraction_grid_3_4"4. 975-735=240"
lab var substraction_grid_3num_corr"Number_of items correct"
lab var substraction_strategy_1"Finger marks/ticks"
lab var substraction_strategy_2"Paper and pencil"
lab var substraction_strategy_3"Mental arithmetic"
lab var correct_substraction_grid_1"Enumerator: Number of corrects in substraction grid 1"
lab var correct_substraction_grid_2"Enumerator: Number of corrects in substraction grid 2"

lab var digital_discrimination_1_1"a. 3"
lab var digital_discrimination_1_2"b. 8"
lab var digital_discrimination_1_3"c. 7"
lab var digital_discrimination_1_4"d. 5"
lab var digital_discrimination_1num_corr"Number of items correct"
lab var digital_discrimination_2_1"a. 86"
lab var digital_discrimination_2_2"b. 79"
lab var digital_discrimination_2_3"c. 49"
lab var digital_discrimination_2_4"d. 42"
lab var digital_discrimination_2num_corr"Number of items correct"
lab var digital_discrimination_3_1"a. 534"
lab var digital_discrimination_3_2"b. 728"
lab var digital_discrimination_3_3"c. 256"
lab var digital_discrimination_3_4"d. 438"
lab var digital_discrimination_3num_corr"Number of items correct"
lab var correct_dd_grid_1"Enumerator: Number of corrects in digital discrimination grid 1"
lab var correct_dd_grid_2"Enumerator: Number of corrects in digital discrimination grid 2"

lab var counting_grid_1_1"How many giraffes do you see here? a. 2"
lab var counting_grid_2_1"How many birds do you see here? b. 5"
lab var counting_grid_3_1"How many pencils do you see here? c. 7"
lab var counting_grid_4_1"How many cars do you see here? d. 9"
lab var counting_grid_5_1"How many trees do you see here? e. 14"
lab var counting_grid_6_1"How many peppers do you see here? f. 12"

lab var number_grid_1_1"a. 5"
lab var number_grid_1_2"b. 8"
lab var number_grid_1_3"c. 4"
lab var number_grid_1_4"d. 2"
lab var number_grid_1_5"e. 1"
lab var number_grid_1_6"f. 9"
lab var number_grid_1_7"g. 7"
lab var number_grid_1_8"h. 10"
lab var number_grid_1num_corr"Number of items correct"
lab var number_grid_2_1"a. 12"
lab var number_grid_2_2"b. 14"
lab var number_grid_2_3"c. 19"
lab var number_grid_2_4"d. 20"
lab var number_grid_2_5"e. 26"
lab var number_grid_2_6"f. 32"
lab var number_grid_2_7"g. 60"
lab var number_grid_2_8"h. 99"
lab var number_grid_2num_corr"Number of items correct"
lab var number_grid_3_1"a. 100"
lab var number_grid_3_2"b. 400"
lab var number_grid_3_3"c. 900"
lab var number_grid_3_4"d. 106"
lab var number_grid_3_5"e. 347"
lab var number_grid_3_6"f. 214"
lab var number_grid_3_7"g. 839"
lab var number_grid_3_8"h. 686"
lab var number_grid_3num_corr"Number of items correct"
lab var correct_number_grid_1"Enumerator: Number of corrects in number grid 1"
lab var correct_number_grid_2"Enumerator: Number of corrects in number grid 2"

lab var Gender"Gender of child:"
lab var Age"How old are you ?"
lab var Grade"What grade are you in now?"
lab var B7"During the last full week of school, how many days did you miss?"

lab var gpsaccuracy"GPS Accuracy"
lab var gpslatitude"GPS Latitude"
lab var gpslongitude"GPS Longitude"

lab var IEF"IEF"
lab var Commune"Commune"
lab var Ecole"Ecole"
lab var Niveau"Niveau"
lab var Sexe"Sexe"
lab var Eleve_nom"Eleve_nom"
lab var CLASSE_NUM"CLASSE_NUM"

//che for n_classes
lab var reading_comprehension_q1"What day do they have fun? [Dimaas]"
lab var reading_comprehension_q2"Where are Ali and his little brother? [in the court; at school, etc]"
lab var reading_comprehension_q3"What does Sidi bring with him? [a ball]"
lab var reading_comprehension_q4"Who plays ball? [Ali; Sidi; his brother; Ali and Sidi; etc.]"
lab var reading_comprehension_q5"How are the children at the end of Game? [happy]"
lab var reading_comprehension_q6"Why are they happy? [they have played well; etc.]"

lab var picture_matching_q1selection"1.The child runs."
lab var picture_matching_q2selection"2.People drink."
lab var picture_matching_q3selection"3.Children plant trees"
lab var picture_matching_q4selection"4.People make music."
lab var picture_matching_q5selection"5.The boy and the girl are looking out the window."
lab var picture_matching_q6selection"6.It was a little cold today. I needed my blanket to fall asleep."
lab var picture_matching_q7selection"7.People gather to make food together. They all add food to the pot."
lab var picture_matching_q8selection"8.The two boys are good friends. They like to sit under the tree and tell each other stories."
lab var picture_matching_q9selection"9.I love my mother. She works hard to take care of my family. I enjoy spending time with her. We enjoy cooking together. I am very grateful to my mother."
lab var picture_matching_q10selection"10.A group of friends gather to play after school. They sing some of the songs but they have no instruments. They usually play tide, jump rope or cat."
lab var picture_matching_q11selection"11.I love my mother. He is kind and loves his children. He works hard to provide for his family. Sometimes she works at the same time as babysitting! It always amazes me how selfless she is and how she carries her child. I am so grateful to my mother."