*****************************************************************************************************************
**Variable labelling
*****************************************************************************************************************
*****///////////*Recheck the assessment labelling......///////////////
*******Student Survey Literacy
lab var  interviewer_type"Are you the census taker observing or speaking?"
lab var  IA"IA"
lab var  IEF"IEF"
lab var Arrondissement"Arrondissement"
lab var Commune"Commune"
lab var tabletUserName"Tablet registered user"
lab var  Ecole"Ecole"
lab var Groupe"Groupe"
lab var  Language"Language of interview"
lab var Intro_Q1"What do you like to do when you're not in school?"
lab var  Intro_Q2"What do you like to play?"
lab var  B2_S"Please specify gender of student"
foreach x in semantic_recording_1 semantic_recording_2 semantic_recording_3 semantic_recording_4{
	lab var  `x'"Enumerator: Voice record the student Semantic"
}

foreach y in word_count_language_1 word_count_language_2 word_count_language_3 word_count_language_4{
	lab var  `y'"ENTER NUMBER OF CORRECT WORDS SPOKEN IN THIS LANGUAGE IN 60 SECONDS…………"
}

foreach z in interviewer_semantic_1 interviewer_semantic_2 interviewer_semantic_3 interviewer_semantic_4{
	lab var  `z'"What is your level of confidence in accurately counting the words in"
}
lab var phonological_awareness_fr_1"1. jour	/j/"
lab var phonological_awareness_fr_2"2. dur	/d/"
lab var phonological_awareness_fr_3"3. lac	/l/"
lab var phonological_awareness_fr_4"4. sac	/s/"
lab var phonological_awareness_fr_5"5. car	/k/"
lab var phonological_awareness_fr_6"6. par	/p/"
lab var phonological_awareness_fr_7"7. tous	/t/"
lab var phonological_awareness_fr_8"8. fille /f/"
lab var phonological_awareness_fr_9"9. balle /b/"
lab var phonological_awareness_fr_10"10. vol /v/"
lab var  phonological_awareness_wf_1"1. jiss /j/"
lab var  phonological_awareness_wf_2"2. dal /d/"
lab var  phonological_awareness_wf_3"3. lakk /l/"
lab var  phonological_awareness_wf_4"4. sakk /s/"
lab var  phonological_awareness_wf_5"5. Kar /k/"
lab var  phonological_awareness_wf_6"6. par /p/"
lab var  phonological_awareness_wf_7"7. tas /t/"
lab var  phonological_awareness_wf_8"8. fal /f/"
lab var  phonological_awareness_wf_9"9. bol /b/"
lab var  phonological_awareness_wf_10"10. wal /w/"
lab var  phonological_awareness_sr_1"1. jeem  /j/"
lab var  phonological_awareness_sr_2"2. dam /d/"
lab var  phonological_awareness_sr_3"3. leel /l/"
lab var  phonological_awareness_sr_4"4. saak /s/"
lab var  phonological_awareness_sr_5"5. kaar /k/"
lab var  phonological_awareness_sr_6"6. pas /p/"
lab var  phonological_awareness_sr_7"7. tol /t/"
lab var  phonological_awareness_sr_8"8. faaɓ /f/"
lab var  phonological_awareness_sr_9"9. bal /b/"
lab var  phonological_awareness_sr_10"10. woli /W/"
lab var  phonological_awareness_pr_1"1. jealous  /j/"
lab var  phonological_awareness_pr_2"2. duro /d/"
lab var  phonological_awareness_pr_3"3. laru /L/"
lab var  phonological_awareness_pr_4"4. saak /s/"
lab var  phonological_awareness_pr_5"5. kaar /k/"
lab var  phonological_awareness_pr_6"6. pos /p/"
lab var  phonological_awareness_pr_7"7. teel /t/"
lab var  phonological_awareness_pr_8"8. felo /f/"
lab var  phonological_awareness_pr_9"9. ball /b/"
lab var  phonological_awareness_pr_10"10. ƴelo /ƴ/"
foreach a in phonological_stop_pr phonological_stop_sr phonological_stop_wf phonological_stop_fr{
	lab var  `a'"Interviewer: Was the stop rule triggered?"
}
lab var  fr_ov_picture_matching_q1"1. Moto"
lab var  fr_ov_picture_matching_q2"2. Feu"
lab var  fr_ov_picture_matching_q3"3. Chemise"
lab var  fr_ov_picture_matching_q4"4. Chaise"
lab var  fr_ov_picture_matching_q5"5. Serpent"
lab var  fr_ov_picture_matching_q6"6. Pantalon"
lab var  fr_ov_picture_matching_q7"7. Poule"
lab var  fr_ov_picture_matching_q8"8. Garçon"
lab var  fr_ov_picture_matching_q9"9. Livre"
lab var  fr_ov_picture_matching_q10"10. Vélo"
lab var  fr_ov_picture_matching_q11"11. Four"
lab var  fr_ov_picture_matching_q12"12. Addition"
lab var  fr_ov_picture_matching_q13"13. Subtraction"
lab var  fr_ov_picture_matching_q14"14. Les livres sur la chaise"
lab var  fr_ov_picture_matching_q15"15. La Ballon sous la table"
lab var  fr_oral_vocabulary_example_2"papillon "
lab var  fr_oral_vocabulary_example_1"fleur "

lab var  wf_ov_picture_matching_q9"9. Téere"
lab var  wf_ov_picture_matching_q8"8. Waxabaane (xale bu góor)"
lab var  wf_ov_picture_matching_q7"7. Ginaar (ganaar)"
lab var  wf_ov_picture_matching_q6"6. Tubay (pãtaloŋ)"
lab var  wf_ov_picture_matching_q5"5. Jaan"
lab var  wf_ov_picture_matching_q4"4. Siis (toogukaay, toogu)"
lab var  wf_ov_picture_matching_q3"3. Simis"
lab var  wf_ov_picture_matching_q2"2. Safara (tàkk-tàkk)"
lab var  wf_ov_picture_matching_q1"1. Moto, (welo, jakarta)"
lab var  wf_ov_picture_matching_q15"15. Bal bà ngi ci suufu taabal"
lab var  wf_ov_picture_matching_q14"14. Tere yà ngi ci kaw siis bi"
lab var  wf_ov_picture_matching_q13"13. Pexem wàññi"
lab var  wf_ov_picture_matching_q12"12. Pexem yokk"
lab var  wf_ov_picture_matching_q11"11. Ñeent"
lab var  wf_ov_picture_matching_q10"10. Welo"
lab var  wf_oral_vocabulary_example_2"papillon "
lab var  wf_oral_vocabulary_example_1"fleur "

lab var  sr_ov_picture_matching_q9"9. Safe"
lab var  sr_ov_picture_matching_q8"8. O njaaƈ o ngoor"
lab var  sr_ov_picture_matching_q7"7. A  cek"
lab var  sr_ov_picture_matching_q6"6. Pantalon"
lab var  sr_ov_picture_matching_q5"5. Fanqool"
lab var  sr_ov_picture_matching_q4"4. A  siis"
lab var  sr_ov_picture_matching_q3"3. Simis"
lab var  sr_ov_picture_matching_q2"2. Fiɗel"
lab var  sr_ov_picture_matching_q15"15. O bal ole yoora taabul ale"
lab var  sr_ov_picture_matching_q14"14. A safe ke took a siis ale"
lab var  sr_ov_picture_matching_q13"13. A baajrand"
lab var  sr_ov_picture_matching_q12"12. A ƥaatrand"
lab var  sr_ov_picture_matching_q11"11. Nahik"
lab var  sr_ov_picture_matching_q10"10. Welo"
lab var  sr_ov_picture_matching_q1"1. Moto"
lab var  sr_oral_vocabulary_example_2"papillon "
lab var  sr_oral_vocabulary_example_1"fleur "

lab var  pr_ov_picture_matching_q9"9. Deftere"
lab var  pr_ov_picture_matching_q8"8. Cukalel gorel"
lab var  pr_ov_picture_matching_q7"7. Gertooɗe"
lab var  pr_ov_picture_matching_q6"6. Laana"
lab var  pr_ov_picture_matching_q5"5. Mboɗdi"
lab var  pr_ov_picture_matching_q4"4. Paɗe"
lab var  pr_ov_picture_matching_q3"3. Ndiwoowa"
lab var  pr_ov_picture_matching_q2"2. Paaɓal"
lab var  pr_ov_picture_matching_q15"15. Ball o ena less tabal"
lab var  pr_ov_picture_matching_q14"14. Defteɗe nena dow jonde"
lab var  pr_ov_picture_matching_q13"13. Ustugol"
lab var  pr_ov_picture_matching_q12"12. Ɓeydugol"
lab var  pr_ov_picture_matching_q11"11. Nayi"
lab var  pr_ov_picture_matching_q10"10. Puccel-njamndi"
lab var  pr_ov_picture_matching_q1"1. Paaɓal"
lab var  pr_oral_vocabulary_example_2"papillon "
lab var  pr_oral_vocabulary_example_1"fleur "

foreach b in letter_knowledge_recording_fr letter_knowledge_recording_wf letter_knowledge_recording_sr letter_knowledge_recording_pr{
	lab var  `b'"Enumerator: Voice record the student Letter knowledge"
}
lab var letter_knowledge_fr_1"1. n"
lab var letter_knowledge_fr_2"2. a"
lab var letter_knowledge_fr_3"3. k"
lab var letter_knowledge_fr_4"4. z"
lab var letter_knowledge_fr_5"5. d"
lab var letter_knowledge_fr_6"6. B"
lab var letter_knowledge_fr_7"7. P"
lab var letter_knowledge_fr_8"8. J"
lab var letter_knowledge_fr_9"9. v"
lab var letter_knowledge_fr_10"10. J"
lab var letter_knowledge_fr_11"11. P"
lab var letter_knowledge_fr_12"12. j"
lab var letter_knowledge_fr_13"13. u"
lab var letter_knowledge_fr_14"14. n"
lab var letter_knowledge_fr_15"15. h"
lab var letter_knowledge_fr_16"16. U"
lab var letter_knowledge_fr_17"17. g"
lab var letter_knowledge_fr_18"18. z"
lab var letter_knowledge_fr_19"19. G"
lab var letter_knowledge_fr_20"20. L"

lab var letter_knowledge_fr_B_1"1. Z"
lab var letter_knowledge_fr_B_2"2. c"
lab var letter_knowledge_fr_B_3"3. S"
lab var letter_knowledge_fr_B_4"4. V"
lab var letter_knowledge_fr_B_5"5. X"
lab var letter_knowledge_fr_B_6"6. y"
lab var letter_knowledge_fr_B_7"7. r"
lab var letter_knowledge_fr_B_8"8. i"
lab var letter_knowledge_fr_B_9"9. g"
lab var letter_knowledge_fr_B_10"10. s"
lab var letter_knowledge_fr_B_11"11. w"
lab var letter_knowledge_fr_B_12"12. f"
lab var letter_knowledge_fr_B_13"13. G"
lab var letter_knowledge_fr_B_14"14. M"
lab var letter_knowledge_fr_B_15"15. R"
lab var letter_knowledge_fr_B_16"16. H"
lab var letter_knowledge_fr_B_17"17. C"
lab var letter_knowledge_fr_B_18"18. u"
lab var letter_knowledge_fr_B_19"19. o"
lab var letter_knowledge_fr_B_20"20. q"
lab var letter_knowledge_fr_B_21"21. U"
lab var letter_knowledge_fr_B_22"22. X"
lab var letter_knowledge_fr_B_23"23. t"
lab var letter_knowledge_fr_B_24"24. E"
lab var letter_knowledge_fr_B_25"25. K"
lab var letter_knowledge_fr_B_26"26. a"
lab var letter_knowledge_fr_B_27"27. p"
lab var letter_knowledge_fr_B_28"28. t"
lab var letter_knowledge_fr_B_29"29. K"
lab var letter_knowledge_fr_B_30"30. ç"
lab var letter_knowledge_fr_B_31"31. D"
lab var letter_knowledge_fr_B_32"32. r"
lab var letter_knowledge_fr_B_33"33. x"
lab var letter_knowledge_fr_B_34"34. W"
lab var letter_knowledge_fr_B_35"35. y"
lab var letter_knowledge_fr_B_36"36. b"

lab var letter_knowledge_wf_1"1. e"
lab var letter_knowledge_wf_2"2. X"
lab var letter_knowledge_wf_3"3. F"
lab var letter_knowledge_wf_4"4. mb"
lab var letter_knowledge_wf_5"5. D"
lab var letter_knowledge_wf_6"6. U"
lab var letter_knowledge_wf_7"7. é"
lab var letter_knowledge_wf_8"8. G"
lab var letter_knowledge_wf_9"9. q"
lab var letter_knowledge_wf_10"10. y"
lab var letter_knowledge_wf_11"11. X"
lab var letter_knowledge_wf_12"12. P"
lab var letter_knowledge_wf_13"13. m"
lab var letter_knowledge_wf_14"14. z"
lab var letter_knowledge_wf_15"15. ë"
lab var letter_knowledge_wf_16"16. v"
lab var letter_knowledge_wf_17"17. c"
lab var letter_knowledge_wf_18"18. Ng"
lab var letter_knowledge_wf_19"19. ù"
lab var letter_knowledge_wf_20"20. d"

lab var letter_knowledge_wf_B_1"1. ŋ"
lab var letter_knowledge_wf_B_2"2. Nq"
lab var letter_knowledge_wf_B_3"3. n"
lab var letter_knowledge_wf_B_4"4. r"
lab var letter_knowledge_wf_B_5"5. ó"
lab var letter_knowledge_wf_B_6"6. À"
lab var letter_knowledge_wf_B_7"7. ù"
lab var letter_knowledge_wf_B_8"8. o"
lab var letter_knowledge_wf_B_9"9. p"
lab var letter_knowledge_wf_B_10"10. c"
lab var letter_knowledge_wf_B_11"11. à"
lab var letter_knowledge_wf_B_12"12. q"
lab var letter_knowledge_wf_B_13"13. V"
lab var letter_knowledge_wf_B_14"14. T"
lab var letter_knowledge_wf_B_15"15. O"
lab var letter_knowledge_wf_B_16"16. nd"
lab var letter_knowledge_wf_B_17"17. W"
lab var letter_knowledge_wf_B_18"18. x"
lab var letter_knowledge_wf_B_19"19. z"
lab var letter_knowledge_wf_B_20"20. k"
lab var letter_knowledge_wf_B_21"21. ù"
lab var letter_knowledge_wf_B_22"22. ñ"
lab var letter_knowledge_wf_B_23"23. Q"
lab var letter_knowledge_wf_B_24"24. P"
lab var letter_knowledge_wf_B_25"25. i"
lab var letter_knowledge_wf_B_26"26. Ñ"
lab var letter_knowledge_wf_B_27"27. f"
lab var letter_knowledge_wf_B_28"28. N"
lab var letter_knowledge_wf_B_29"29. I"
lab var letter_knowledge_wf_B_30"30. K"
lab var letter_knowledge_wf_B_31"31. w"
lab var letter_knowledge_wf_B_32"32. Ó"
lab var letter_knowledge_wf_B_33"33. B"
lab var letter_knowledge_wf_B_34"34. J"
lab var letter_knowledge_wf_B_35"35. Ë"
lab var letter_knowledge_wf_B_36"36. R"

lab var letter_knowledge_sr_1"1. aa"
lab var letter_knowledge_sr_2"2. a"
lab var letter_knowledge_sr_3"3. p"
lab var letter_knowledge_sr_4"4. h"
lab var letter_knowledge_sr_5"5. R"
lab var letter_knowledge_sr_6"6. y"
lab var letter_knowledge_sr_7"7. h"
lab var letter_knowledge_sr_8"8. A"
lab var letter_knowledge_sr_9"9. ŋ"
lab var letter_knowledge_sr_10"10. b"
lab var letter_knowledge_sr_11"11. N"
lab var letter_knowledge_sr_12"12. B"
lab var letter_knowledge_sr_13"13. ƴ"
lab var letter_knowledge_sr_14"14. i"
lab var letter_knowledge_sr_15"15. C"
lab var letter_knowledge_sr_16"16. d"
lab var letter_knowledge_sr_17"17. s"
lab var letter_knowledge_sr_18"18. n"
lab var letter_knowledge_sr_19"19. U"
lab var letter_knowledge_sr_20"20. f"

lab var letter_knowledge_sr_B_1"1. D"
lab var letter_knowledge_sr_B_2"2. ii"
lab var letter_knowledge_sr_B_3"3. Ñ"
lab var letter_knowledge_sr_B_4"4. q"
lab var letter_knowledge_sr_B_5"5. w"
lab var letter_knowledge_sr_B_6"6. W"
lab var letter_knowledge_sr_B_7"7. g"
lab var letter_knowledge_sr_B_8"8. l"
lab var letter_knowledge_sr_B_9"9. G"
lab var letter_knowledge_sr_B_10"10. C"
lab var letter_knowledge_sr_B_11"11. t"
lab var letter_knowledge_sr_B_12"12. o"
lab var letter_knowledge_sr_B_13"13. Y"
lab var letter_knowledge_sr_B_14"14. t"
lab var letter_knowledge_sr_B_15"15. K"
lab var letter_knowledge_sr_B_16"16. H"
lab var letter_knowledge_sr_B_17"17. k"
lab var letter_knowledge_sr_B_18"18. oo"
lab var letter_knowledge_sr_B_19"19. E"
lab var letter_knowledge_sr_B_20"20. H"
lab var letter_knowledge_sr_B_21"21. j"
lab var letter_knowledge_sr_B_22"22. x"
lab var letter_knowledge_sr_B_23"23. T"
lab var letter_knowledge_sr_B_24"24. A"
lab var letter_knowledge_sr_B_25"25. Ŋ"
lab var letter_knowledge_sr_B_26"26. k"
lab var letter_knowledge_sr_B_27"27. ee"
lab var letter_knowledge_sr_B_28"28. L"
lab var letter_knowledge_sr_B_29"29. M"
lab var letter_knowledge_sr_B_30"30. ñ"
lab var letter_knowledge_sr_B_31"31. I"
lab var letter_knowledge_sr_B_32"32. u"
lab var letter_knowledge_sr_B_33"33. J"
lab var letter_knowledge_sr_B_34"34. X"
lab var letter_knowledge_sr_B_35"35. uu"
lab var letter_knowledge_sr_B_36"36. r"

lab var letter_knowledge_pr_1"1. D"
lab var letter_knowledge_pr_2"2. k"
lab var letter_knowledge_pr_3"3. b"
lab var letter_knowledge_pr_4"4. M"
lab var letter_knowledge_pr_5"5. q"
lab var letter_knowledge_pr_6"6. w"
lab var letter_knowledge_pr_7"7. j"
lab var letter_knowledge_pr_8"8. g"
lab var letter_knowledge_pr_9"9. h"
lab var letter_knowledge_pr_10"10. e"
lab var letter_knowledge_pr_11"11. P"
lab var letter_knowledge_pr_12"12. U"
lab var letter_knowledge_pr_13"13. ƴ"
lab var letter_knowledge_pr_14"14. Y"
lab var letter_knowledge_pr_15"15. p"
lab var letter_knowledge_pr_16"16. x"
lab var letter_knowledge_pr_17"17. Ɗ"
lab var letter_knowledge_pr_18"18. p"
lab var letter_knowledge_pr_19"19. y"
lab var letter_knowledge_pr_20"20. b"

lab var letter_knowledge_pr_B_1"1. S"
lab var letter_knowledge_pr_B_2"2. h"
lab var letter_knowledge_pr_B_3"3. ɗ"
lab var letter_knowledge_pr_B_4"4. N"
lab var letter_knowledge_pr_B_5"5. H"
lab var letter_knowledge_pr_B_6"6. nj"
lab var letter_knowledge_pr_B_7"7. O"
lab var letter_knowledge_pr_B_8"8. ng"
lab var letter_knowledge_pr_B_9"9. E"
lab var letter_knowledge_pr_B_10"10. Ɓ"
lab var letter_knowledge_pr_B_11"11. Ñ"
lab var letter_knowledge_pr_B_12"12. s"
lab var letter_knowledge_pr_B_13"13. B"
lab var letter_knowledge_pr_B_14"14. Ŋ"
lab var letter_knowledge_pr_B_15"15. T"
lab var letter_knowledge_pr_B_16"16. U"
lab var letter_knowledge_pr_B_17"17. ND"
lab var letter_knowledge_pr_B_18"18. l"
lab var letter_knowledge_pr_B_19"19. k"
lab var letter_knowledge_pr_B_20"20. O"
lab var letter_knowledge_pr_B_21"21. sh"
lab var letter_knowledge_pr_B_22"22. nd"
lab var letter_knowledge_pr_B_23"23. C"
lab var letter_knowledge_pr_B_24"24. g"
lab var letter_knowledge_pr_B_25"25. MB"
lab var letter_knowledge_pr_B_26"26. F"
lab var letter_knowledge_pr_B_27"27. c"
lab var letter_knowledge_pr_B_28"28. o"
lab var letter_knowledge_pr_B_29"29. n"
lab var letter_knowledge_pr_B_30"30. R"
lab var letter_knowledge_pr_B_31"31. W"
lab var letter_knowledge_pr_B_32"32. Z"
lab var letter_knowledge_pr_B_33"33. D"
lab var letter_knowledge_pr_B_34"34. a"
lab var letter_knowledge_pr_B_35"35. y"
lab var letter_knowledge_pr_B_36"36. J"

foreach c in letter_knowledge_stop_fr letter_knowledge_stop_wf letter_knowledge_stop_sr letter_knowledge_stop_pr{
	lab var `c'"Interviewer: Was the stop rule triggered Letter knowledge?"
}

foreach d in letter_knowledge_reason_fr letter_knowledge_reason_wf letter_knowledge_reason_sr letter_knowledge_reason_pr{
	lab var `d'"Interviewer: Of the letters that students pronounced incorrectly, were many of them incorrect because they named the letter instead of making the sound?"
}


lab var read_familiar_words_fr_1"tu"
lab var read_familiar_words_fr_2"ou"
lab var read_familiar_words_fr_3"il"
lab var read_familiar_words_fr_4"ma"
lab var read_familiar_words_fr_5"or"
lab var read_familiar_words_fr_6"ami"
lab var read_familiar_words_fr_7"sac"
lab var read_familiar_words_fr_8"nom"
lab var read_familiar_words_fr_9"mon"
lab var read_familiar_words_fr_10"10. sur"
lab var read_familiar_words_fr_11"11. lit"
lab var read_familiar_words_fr_12"12. bébé"
lab var read_familiar_words_fr_13"13. papa"
lab var read_familiar_words_fr_14"14. dans"
lab var read_familiar_words_fr_15"15. peau"
lab var read_familiar_words_fr_16"16. lire"
lab var read_familiar_words_fr_17"17. pain"
lab var read_familiar_words_fr_18"18. têtu"
lab var read_familiar_words_fr_19"19. monde"
lab var read_familiar_words_fr_20"20. faire"

lab var read_familiar_words_fr_B_1"1. demain"
lab var read_familiar_words_fr_B_2"2. porter"
lab var read_familiar_words_fr_B_3"3. rougir"
lab var read_familiar_words_fr_B_4"4. façade"
lab var read_familiar_words_fr_B_5"5. chaise"
lab var read_familiar_words_fr_B_6"6. dormir"
lab var read_familiar_words_fr_B_7"7. logique"
lab var read_familiar_words_fr_B_8"8. fauteuil"
lab var read_familiar_words_fr_B_9"9. studieux"
lab var read_familiar_words_fr_B_10"10. grandeur"
lab var read_familiar_words_fr_B_11"11. grenouille"
lab var read_familiar_words_fr_B_12"12. beaucoup"
lab var read_familiar_words_fr_B_13"13. aujourd`hui"
lab var read_familiar_words_fr_B_14"14. maintenant"
lab var read_familiar_words_fr_B_15"15. comprendre"


lab var read_familiar_words_wf_1"1. am"
lab var read_familiar_words_wf_2"2. po"
lab var read_familiar_words_wf_3"3. añ"
lab var read_familiar_words_wf_4"4. tan"
lab var read_familiar_words_wf_5"5. jël"
lab var read_familiar_words_wf_6"6. bal"
lab var read_familiar_words_wf_7"7. nun"
lab var read_familiar_words_wf_8"8. fan"
lab var read_familiar_words_wf_9"9. kër"
lab var read_familiar_words_wf_10"10. bët"
lab var read_familiar_words_wf_11"11. bari"
lab var read_familiar_words_wf_12"12. muus"
lab var read_familiar_words_wf_13"13. suuf"
lab var read_familiar_words_wf_14"14. dara"
lab var read_familiar_words_wf_15"15. néeg"
lab var read_familiar_words_wf_16"16. tool"
lab var read_familiar_words_wf_17"17. yaay"
lab var read_familiar_words_wf_18"18. rafet"
lab var read_familiar_words_wf_19"19. xonk"
lab var read_familiar_words_wf_20"20. woto"
lab var read_familiar_words_wf_B_1"1. jàng"
lab var read_familiar_words_wf_B_2"2. kaay"
lab var read_familiar_words_wf_B_3"3. dëkk"
lab var read_familiar_words_wf_B_4"4. démb"
lab var read_familiar_words_wf_B_5"5. koor"
lab var read_familiar_words_wf_B_6"6. itam"
lab var read_familiar_words_wf_B_7"7. téggu"
lab var read_familiar_words_wf_B_8"8. ragal"
lab var read_familiar_words_wf_B_9"9. caabi"
lab var read_familiar_words_wf_B_10"10. wurus"
lab var read_familiar_words_wf_B_11"11. ekool"
lab var read_familiar_words_wf_B_12"12. gàddu"
lab var read_familiar_words_wf_B_13"13. kaani"
lab var read_familiar_words_wf_B_14"14. xaalis"
lab var read_familiar_words_wf_B_15"15. taabal"

lab var read_familiar_words_pr_1"1. ɗam"
lab var read_familiar_words_pr_2"2. ima"
lab var read_familiar_words_pr_3"3. foti"
lab var read_familiar_words_pr_4"4. ŋam"
lab var read_familiar_words_pr_5"5. kule"
lab var read_familiar_words_pr_6"6. nana"
lab var read_familiar_words_pr_7"7. wuro"
lab var read_familiar_words_pr_8"8. aade"
lab var read_familiar_words_pr_9"9. ñaam"
lab var read_familiar_words_pr_10"10. oyna"
lab var read_familiar_words_pr_11"11. ɗiɗi"
lab var read_familiar_words_pr_12"12. ngesa"
lab var read_familiar_words_pr_13"13. hawru"
lab var read_familiar_words_pr_14"14. shiri"
lab var read_familiar_words_pr_15"15. bimbi"
lab var read_familiar_words_pr_16"16. golle"
lab var read_familiar_words_pr_17"17. dotti"
lab var read_familiar_words_pr_18"18. lamɗo"
lab var read_familiar_words_pr_19"19. moƴƴi"
lab var read_familiar_words_pr_20"20. ceede"
lab var read_familiar_words_pr_B_1"1. rewɓe"
lab var read_familiar_words_pr_B_2"2. qawre"
lab var read_familiar_words_pr_B_3"3. ndiyam"
lab var read_familiar_words_pr_B_4"4. zawre"
lab var read_familiar_words_pr_B_5"5. xamle"
lab var read_familiar_words_pr_B_6"6. yimɓe"
lab var read_familiar_words_pr_B_7"7. sagata"
lab var read_familiar_words_pr_B_8"8. ndaaru"
lab var read_familiar_words_pr_B_9"9. jannoo"
lab var read_familiar_words_pr_B_10"10. njoɓdi"
lab var read_familiar_words_pr_B_11"11. ummora"
lab var read_familiar_words_pr_B_12"12. enndam"
lab var read_familiar_words_pr_B_13"13. pulaaku"
lab var read_familiar_words_pr_B_14"14. ƴettude"
lab var read_familiar_words_pr_B_15"15. immunde"

lab var read_familiar_words_sr_1"1. mu"
lab var read_familiar_words_sr_2"2. ta"
lab var read_familiar_words_sr_3"3. el"
lab var read_familiar_words_sr_4"4. ma"
lab var read_familiar_words_sr_5"5. ra"
lab var read_familiar_words_sr_6"6. sa"
lab var read_familiar_words_sr_7"7. as"
lab var read_familiar_words_sr_8"8. ool"
lab var read_familiar_words_sr_9"9. lad"
lab var read_familiar_words_sr_10"10. mal"
lab var read_familiar_words_sr_11"11. las"
lab var read_familiar_words_sr_12"12. dab"
lab var read_familiar_words_sr_13"13. lay"
lab var read_familiar_words_sr_14"14. ƴax"
lab var read_familiar_words_sr_15"15. gar"
lab var read_familiar_words_sr_16"16. faal"
lab var read_familiar_words_sr_17"17. woos"
lab var read_familiar_words_sr_18"18. eeti"
lab var read_familiar_words_sr_19"19. niir"
lab var read_familiar_words_sr_20"20. room"
lab var read_familiar_words_sr_B_1"bulo"
lab var read_familiar_words_sr_B_2"ndok"
lab var read_familiar_words_sr_B_3"soos"
lab var read_familiar_words_sr_B_4"ñaal"
lab var read_familiar_words_sr_B_5"welo"
lab var read_familiar_words_sr_B_6"saas"
lab var read_familiar_words_sr_B_7"naak"
lab var read_familiar_words_sr_B_8"ndol"
lab var read_familiar_words_sr_B_9"moto"
lab var read_familiar_words_sr_B_10"10. raapi"
lab var read_familiar_words_sr_B_11"11. begax"
lab var read_familiar_words_sr_B_12"12. foofi"
lab var read_familiar_words_sr_B_13"13. maafi"
lab var read_familiar_words_sr_B_14"14. moofa"
lab var read_familiar_words_sr_B_15"15. fuloor"

foreach e in read_familiar_stop_pr read_familiar_stop_sr read_familiar_stop_fr read_familiar_stop_wf{
	lab var `e'"Interviewer: Was the stop rule triggered Reading familiar words?"
}

lab var read_invented_words_fr_1"1. ja"
lab var read_invented_words_fr_2"2. tal"
lab var read_invented_words_fr_3"3. zi"
lab var read_invented_words_fr_4"4. ol"
lab var read_invented_words_fr_5"5. vaf"
lab var read_invented_words_fr_6"6. sar"
lab var read_invented_words_fr_7"7. cla"
lab var read_invented_words_fr_8"8. vor"
lab var read_invented_words_fr_9"9. ciko"
lab var read_invented_words_fr_10"10. ul"
lab var read_invented_words_fr_11"11. bige"
lab var read_invented_words_fr_12"12. plovi"
lab var read_invented_words_fr_13"13. neul"
lab var read_invented_words_fr_14"14. bilba"
lab var read_invented_words_fr_15"15. ima"
lab var read_invented_words_fr_16"16. tipa"
lab var read_invented_words_fr_17"17. blu"
lab var read_invented_words_fr_18"18. osi"
lab var read_invented_words_fr_19"19. toche"
lab var read_invented_words_fr_20"20. flir"
lab var read_invented_words_fr_B_1"1. saré"
lab var read_invented_words_fr_B_2"2. rané"
lab var read_invented_words_fr_B_3"3. nur"
lab var read_invented_words_fr_B_4"4. pro"
lab var read_invented_words_fr_B_5"5. duse"
lab var read_invented_words_fr_B_6"6. mouli"
lab var read_invented_words_fr_B_7"7. clo"
lab var read_invented_words_fr_B_8"8. chane"
lab var read_invented_words_fr_B_9"9. doupé"
lab var read_invented_words_fr_B_10"10. bape"
lab var read_invented_words_fr_B_11"11. til"
lab var read_invented_words_fr_B_12"12. zopé"
lab var read_invented_words_fr_B_13"13. taindé"
lab var read_invented_words_fr_B_14"14. nube"
lab var read_invented_words_fr_B_15"15. doul"
lab var read_invented_words_fr_B_16"16. donré"
lab var read_invented_words_fr_B_17"17. raite"
lab var read_invented_words_fr_B_18"18. dreu"
lab var read_invented_words_fr_B_19"19. lorpe"
lab var read_invented_words_fr_B_20"20. ibrau"
lab var read_invented_words_fr_B_21"21. oti"
lab var read_invented_words_fr_B_22"22. nogir"
lab var read_invented_words_fr_B_23"23. neau"
lab var read_invented_words_fr_B_24"24. moudir"
lab var read_invented_words_fr_B_25"25. bir"
lab var read_invented_words_fr_B_26"26. bair"
lab var read_invented_words_fr_B_27"27. lépa"
lab var read_invented_words_fr_B_28"28. zode"
lab var read_invented_words_fr_B_29"29. fipe"
lab var read_invented_words_fr_B_30"30. nour"

lab var read_invented_words_wf_1"1. fa"
lab var read_invented_words_wf_2"2. tal"
lab var read_invented_words_wf_3"3. zi"
lab var read_invented_words_wf_4"4. ol"
lab var read_invented_words_wf_5"5. vaf"
lab var read_invented_words_wf_6"6. sar"
lab var read_invented_words_wf_7"7. kal"
lab var read_invented_words_wf_8"8. wor"
lab var read_invented_words_wf_9"9. siko"
lab var read_invented_words_wf_10"10. ul"
lab var read_invented_words_wf_11"11. bik"
lab var read_invented_words_wf_12"12. blabi"
lab var read_invented_words_wf_13"13. nul"
lab var read_invented_words_wf_14"14. bilba"
lab var read_invented_words_wf_15"15. ima"
lab var read_invented_words_wf_16"16. tipa"
lab var read_invented_words_wf_17"17. blu"
lab var read_invented_words_wf_18"18. osi"
lab var read_invented_words_wf_19"19. toss"
lab var read_invented_words_wf_20"20. flir"
lab var read_invented_words_wf_B_1"1. saré"
lab var read_invented_words_wf_B_2"2. rané"
lab var read_invented_words_wf_B_3"3. nur"
lab var read_invented_words_wf_B_4"4. pro"
lab var read_invented_words_wf_B_5"5. dusi"
lab var read_invented_words_wf_B_6"6. muli"
lab var read_invented_words_wf_B_7"7. klo"
lab var read_invented_words_wf_B_8"8. bané"
lab var read_invented_words_wf_B_9"9. dupé"
lab var read_invented_words_wf_B_10"10. bab"
lab var read_invented_words_wf_B_11"11. til"
lab var read_invented_words_wf_B_12"12. zopé"
lab var read_invented_words_wf_B_13"13. nawé"
lab var read_invented_words_wf_B_14"14. nub"
lab var read_invented_words_wf_B_15"15. dal"
lab var read_invented_words_wf_B_16"16. donré"
lab var read_invented_words_wf_B_17"17. rét"
lab var read_invented_words_wf_B_18"18. drë"
lab var read_invented_words_wf_B_19"19. dorbé"
lab var read_invented_words_wf_B_20"20. ibra"
lab var read_invented_words_wf_B_21"21. oti"
lab var read_invented_words_wf_B_22"22. nogir"
lab var read_invented_words_wf_B_23"23. no"
lab var read_invented_words_wf_B_24"24. mudir"
lab var read_invented_words_wf_B_25"25. bir"
lab var read_invented_words_wf_B_26"26. bér"
lab var read_invented_words_wf_B_27"27. lépa"
lab var read_invented_words_wf_B_28"28. fode"
lab var read_invented_words_wf_B_29"29. wipé"
lab var read_invented_words_wf_B_30"30. nur"

lab var read_invented_words_pr_1"1. yes"
lab var read_invented_words_pr_2"2. gal"
lab var read_invented_words_pr_3"3. walk"
lab var read_invented_words_pr_4"4. ol"
lab var read_invented_words_pr_5"5. waf"
lab var read_invented_words_pr_6"6. sat"
lab var read_invented_words_pr_7"7. kiɗ"
lab var read_invented_words_pr_8"8. Bor"
lab var read_invented_words_pr_9"9. ciko"
lab var read_invented_words_pr_10"10. ul"
lab var read_invented_words_pr_11"11. bige"
lab var read_invented_words_pr_12"12. polƴi"
lab var read_invented_words_pr_13"13. Ñal"
lab var read_invented_words_pr_14"14. bilba"
lab var read_invented_words_pr_15"15. ima"
lab var read_invented_words_pr_16"16. tipa"
lab var read_invented_words_pr_17"17. ɓalu"
lab var read_invented_words_pr_18"18. Osi"
lab var read_invented_words_pr_19"19. toce"
lab var read_invented_words_pr_20"20. to spin"
lab var read_invented_words_pr_B_1"1. saru"
lab var read_invented_words_pr_B_2"2. rani"
lab var read_invented_words_pr_B_3"3. Run"
lab var read_invented_words_pr_B_4"4. pud"
lab var read_invented_words_pr_B_5"5. nozzle"
lab var read_invented_words_pr_B_6"6. muli"
lab var read_invented_words_pr_B_7"7. calo"
lab var read_invented_words_pr_B_8"8. Fooj"
lab var read_invented_words_pr_B_9"9. fooled"
lab var read_invented_words_pr_B_10"10. yape"
lab var read_invented_words_pr_B_11"11. until"
lab var read_invented_words_pr_B_12"12. ƴope"
lab var read_invented_words_pr_B_13"13. Tense"
lab var read_invented_words_pr_B_14"14. cloud"
lab var read_invented_words_pr_B_15"15. duuŋ"
lab var read_invented_words_pr_B_16"16. doɓre"
lab var read_invented_words_pr_B_17"17. rete"
lab var read_invented_words_pr_B_18"18. Deefu"
lab var read_invented_words_pr_B_19"19. wolf"
lab var read_invented_words_pr_B_20"20. ibru"
lab var read_invented_words_pr_B_21"21. oti"
lab var read_invented_words_pr_B_22"22. nogir"
lab var read_invented_words_pr_B_23"23. Neƴ"
lab var read_invented_words_pr_B_24"24. mbudiir"
lab var read_invented_words_pr_B_25"25. bir"
lab var read_invented_words_pr_B_26"26. bira"
lab var read_invented_words_pr_B_27"27. leepa"
lab var read_invented_words_pr_B_28"28. Ŋoode"
lab var read_invented_words_pr_B_29"29. fipe"
lab var read_invented_words_pr_B_30"30. ngiir"

lab var read_invented_words_sr_1"1. ja"
lab var read_invented_words_sr_2"2. tap"
lab var read_invented_words_sr_3"3. ton"
lab var read_invented_words_sr_4"4. Yiy"
lab var read_invented_words_sr_5"5. kak"
lab var read_invented_words_sr_6"6. saw"
lab var read_invented_words_sr_7"7. cip"
lab var read_invented_words_sr_8"8. dob"
lab var read_invented_words_sr_9"9. muf"
lab var read_invented_words_sr_10"10. ul"
lab var read_invented_words_sr_11"11. tape"
lab var read_invented_words_sr_12"12. gogi"
lab var read_invented_words_sr_13"13. reba"
lab var read_invented_words_sr_14"14. bilba"
lab var read_invented_words_sr_15"15. emi"
lab var read_invented_words_sr_16"16. tipa"
lab var read_invented_words_sr_17"17. kooke"
lab var read_invented_words_sr_18"18. osi"
lab var read_invented_words_sr_19"19. natu"
lab var read_invented_words_sr_20"20. fosaa"
lab var read_invented_words_sr_B_1"1. ripa"
lab var read_invented_words_sr_B_2"2. ƭupe"
lab var read_invented_words_sr_B_3"3. hojaa"
lab var read_invented_words_sr_B_4"4. bili"
lab var read_invented_words_sr_B_5"5. daas"
lab var read_invented_words_sr_B_6"6. noohe"
lab var read_invented_words_sr_B_7"7. omaa"
lab var read_invented_words_sr_B_8"8. unil"
lab var read_invented_words_sr_B_9"9. moce"
lab var read_invented_words_sr_B_10"10. xiika"
lab var read_invented_words_sr_B_11"11. jooci"
lab var read_invented_words_sr_B_12"12. quuk"
lab var read_invented_words_sr_B_13"13. saagi"
lab var read_invented_words_sr_B_14"14. loona"
lab var read_invented_words_sr_B_15"15. geeji"
lab var read_invented_words_sr_B_16"16. aalaw"
lab var read_invented_words_sr_B_17"17. koon"
lab var read_invented_words_sr_B_18"18. poox"
lab var read_invented_words_sr_B_19"19. liki"
lab var read_invented_words_sr_B_20"20. edildi"
lab var read_invented_words_sr_B_21"21. otin"
lab var read_invented_words_sr_B_22"22. ceewu"
lab var read_invented_words_sr_B_23"23. jooka"
lab var read_invented_words_sr_B_24"24. yuuye"
lab var read_invented_words_sr_B_25"25. olipe"
lab var read_invented_words_sr_B_26"26. hiik"
lab var read_invented_words_sr_B_27"27. meeji"
lab var read_invented_words_sr_B_28"28. sokee"
lab var read_invented_words_sr_B_29"29. emew"
lab var read_invented_words_sr_B_30"30. noori"

foreach f in read_invented_stop_fr read_invented_stop_pr read_invented_stop_sr read_invented_stop_wf{
	lab var `f'"Interviewer: Was the stop rule triggered Reading Invented words?"
}

lab var oral_reading_fluency_fr_1"1. Le"
lab var oral_reading_fluency_fr_2"2. jeu"
lab var oral_reading_fluency_fr_3"3. de"
lab var oral_reading_fluency_fr_4"4. ballon."
lab var oral_reading_fluency_fr_5"5. C'est"
lab var oral_reading_fluency_fr_6"6. samedi."
lab var oral_reading_fluency_fr_7"7. Ali"
lab var oral_reading_fluency_fr_8"8. s'amuse"
lab var oral_reading_fluency_fr_9"9. dans"
lab var oral_reading_fluency_fr_10"10. la"
lab var oral_reading_fluency_fr_11"11. cour"
lab var oral_reading_fluency_fr_12"12. de"
lab var oral_reading_fluency_fr_13"13. l'école"
lab var oral_reading_fluency_fr_14"14. avec"
lab var oral_reading_fluency_fr_15"15. son"
lab var oral_reading_fluency_fr_16"16. petit"
lab var oral_reading_fluency_fr_17"17. frère."
lab var oral_reading_fluency_fr_18"18. Son"
lab var oral_reading_fluency_fr_19"19. camarade"
lab var oral_reading_fluency_fr_20"20. Sidi"
lab var oral_reading_fluency_fr_21"21. arrive"
lab var oral_reading_fluency_fr_22"22. avec"
lab var oral_reading_fluency_fr_23"23. un"
lab var oral_reading_fluency_fr_24"24. ballon."
lab var oral_reading_fluency_fr_25"25. Ali,"
lab var oral_reading_fluency_fr_26"26. son"
lab var oral_reading_fluency_fr_27"27. frère"
lab var oral_reading_fluency_fr_28"28. et"
lab var oral_reading_fluency_fr_29"29. Sidi"
lab var oral_reading_fluency_fr_30"30. jouent"
lab var oral_reading_fluency_fr_31"31. au"
lab var oral_reading_fluency_fr_32"32. ballon"
lab var oral_reading_fluency_fr_33"33. toute"
lab var oral_reading_fluency_fr_34"34. la"
lab var oral_reading_fluency_fr_35"35. matinée."
lab var oral_reading_fluency_fr_36"36. Les"
lab var oral_reading_fluency_fr_37"37. amis"
lab var oral_reading_fluency_fr_38"38. ont"
lab var oral_reading_fluency_fr_39"39. bien"
lab var oral_reading_fluency_fr_40"40. joué."
lab var oral_reading_fluency_fr_41"41. Ils"
lab var oral_reading_fluency_fr_42"42. sont"
lab var oral_reading_fluency_fr_43"43. contents."

lab var oral_reading_fluency_wf_1"1. Powum"
lab var oral_reading_fluency_wf_2"2. bal."
lab var oral_reading_fluency_wf_3"3. Gaawu"
lab var oral_reading_fluency_wf_4"4. la."
lab var oral_reading_fluency_wf_5"5. Aali"
lab var oral_reading_fluency_wf_6"6. mu"
lab var oral_reading_fluency_wf_7"7. ngi"
lab var oral_reading_fluency_wf_8"8. fo"
lab var oral_reading_fluency_wf_9"9. Ci"
lab var oral_reading_fluency_wf_10"10. ëttu"
lab var oral_reading_fluency_wf_11"11. senn"
lab var oral_reading_fluency_wf_12"12. ekool"
lab var oral_reading_fluency_wf_13"13. bi"
lab var oral_reading_fluency_wf_14"14. moom"
lab var oral_reading_fluency_wf_15"15. ak"
lab var oral_reading_fluency_wf_16"16. rakkam"
lab var oral_reading_fluency_wf_17"17. ji."
lab var oral_reading_fluency_wf_18"18. Moroomam"
lab var oral_reading_fluency_wf_19"19. Sidi"
lab var oral_reading_fluency_wf_20"20. eggsi"
lab var oral_reading_fluency_wf_21"21. na"
lab var oral_reading_fluency_wf_22"22. ak"
lab var oral_reading_fluency_wf_23"23. benn"
lab var oral_reading_fluency_wf_24"24. bal."
lab var oral_reading_fluency_wf_25"25. Ali,"
lab var oral_reading_fluency_wf_26"26. rakkam"
lab var oral_reading_fluency_wf_27"27. ji"
lab var oral_reading_fluency_wf_28"28. ak"
lab var oral_reading_fluency_wf_29"29. Sidi"
lab var oral_reading_fluency_wf_30"30. ñu"
lab var oral_reading_fluency_wf_31"31. ngi"
lab var oral_reading_fluency_wf_32"32. futbal"
lab var oral_reading_fluency_wf_33"33. Suba"
lab var oral_reading_fluency_wf_34"34. si"
lab var oral_reading_fluency_wf_35"35. yépp."
lab var oral_reading_fluency_wf_36"36. Xarit"
lab var oral_reading_fluency_wf_37"37. yi"
lab var oral_reading_fluency_wf_38"38. fo"
lab var oral_reading_fluency_wf_39"39. nañu"
lab var oral_reading_fluency_wf_40"40. bu"
lab var oral_reading_fluency_wf_41"41. baax."
lab var oral_reading_fluency_wf_42"42. Bég"
lab var oral_reading_fluency_wf_43"43. nañu."

lab var oral_reading_fluency_sr_1"1. Faŋas"
lab var oral_reading_fluency_sr_2"2. o"
lab var oral_reading_fluency_sr_3"3. bal/"
lab var oral_reading_fluency_sr_4"4. Xaye"
lab var oral_reading_fluency_sr_5"5. refu"
lab var oral_reading_fluency_sr_6"6. ñaal"
lab var oral_reading_fluency_sr_7"7. maak"
lab var oral_reading_fluency_sr_8"8. gaaw."
lab var oral_reading_fluency_sr_9"9. Aali"
lab var oral_reading_fluency_sr_10"10. kaa"
lab var oral_reading_fluency_sr_11"11. ŋasaa"
lab var oral_reading_fluency_sr_12"12. no"
lab var oral_reading_fluency_sr_13"13. maax"
lab var oral_reading_fluency_sr_14"14. ole"
lab var oral_reading_fluency_sr_15"15. ekol"
lab var oral_reading_fluency_sr_16"16. fo"
lab var oral_reading_fluency_sr_17"17. ndeɓum."
lab var oral_reading_fluency_sr_18"18. O"
lab var oral_reading_fluency_sr_19"19. yoonum"
lab var oral_reading_fluency_sr_20"20. Siidi"
lab var oral_reading_fluency_sr_21"21. a"
lab var oral_reading_fluency_sr_22"22. fadiid"
lab var oral_reading_fluency_sr_23"23. fo"
lab var oral_reading_fluency_sr_24"24. bal."
lab var oral_reading_fluency_sr_25"25. Aali,"
lab var oral_reading_fluency_sr_26"26. o"
lab var oral_reading_fluency_sr_27"27. ndeɓum"
lab var oral_reading_fluency_sr_28"28. fa"
lab var oral_reading_fluency_sr_29"29. Siidi"
lab var oral_reading_fluency_sr_30"30. kaa"
lab var oral_reading_fluency_sr_31"31. da"
lab var oral_reading_fluency_sr_32"32. mbalaa."
lab var oral_reading_fluency_sr_33"33. Xa"
lab var oral_reading_fluency_sr_34"34. caaƈ"
lab var oral_reading_fluency_sr_35"35. axe"
lab var oral_reading_fluency_sr_36"36. ŋasaa"
lab var oral_reading_fluency_sr_37"37. nqes"
lab var oral_reading_fluency_sr_38"38. ne"
lab var oral_reading_fluency_sr_39"39. fop,"
lab var oral_reading_fluency_sr_40"40. kam"
lab var oral_reading_fluency_sr_41"41. den"
lab var oral_reading_fluency_sr_42"42. a"
lab var oral_reading_fluency_sr_43"43. ɓuuɓa."

lab var oral_reading_fluency_pr_1"1. Fijirde"
lab var oral_reading_fluency_pr_2"2. pettugol"
lab var oral_reading_fluency_pr_3"3. bal."
lab var oral_reading_fluency_pr_4"4. Ñande"
lab var oral_reading_fluency_pr_5"5. aset."
lab var oral_reading_fluency_pr_6"6. Aali"
lab var oral_reading_fluency_pr_7"7. na"
lab var oral_reading_fluency_pr_8"8. fija"
lab var oral_reading_fluency_pr_9"9. e"
lab var oral_reading_fluency_pr_10"10. nder"
lab var oral_reading_fluency_pr_11"11. dingiral"
lab var oral_reading_fluency_pr_12"12. lekkol"
lab var oral_reading_fluency_pr_13"13. hee"
lab var oral_reading_fluency_pr_14"14. kam"
lab var oral_reading_fluency_pr_15"15. e"
lab var oral_reading_fluency_pr_16"16. miñum"
lab var oral_reading_fluency_pr_17"17. gorko."
lab var oral_reading_fluency_pr_18"18. Sehil"
lab var oral_reading_fluency_pr_19"19. makko"
lab var oral_reading_fluency_pr_20"20. Siidi"
lab var oral_reading_fluency_pr_21"21. ari"
lab var oral_reading_fluency_pr_22"22. na"
lab var oral_reading_fluency_pr_23"23. jogii"
lab var oral_reading_fluency_pr_24"24. bal."
lab var oral_reading_fluency_pr_25"25. Aali,"
lab var oral_reading_fluency_pr_26"26. miñum"
lab var oral_reading_fluency_pr_27"27. gorko"
lab var oral_reading_fluency_pr_28"28. e"
lab var oral_reading_fluency_pr_29"29. Siidi"
lab var oral_reading_fluency_pr_30"30. mbeeti"
lab var oral_reading_fluency_pr_31"31. ko"
lab var oral_reading_fluency_pr_32"32. fettude"
lab var oral_reading_fluency_pr_33"33. subaka"
lab var oral_reading_fluency_pr_34"34. oo"
lab var oral_reading_fluency_pr_35"35. fof."
lab var oral_reading_fluency_pr_36"36. Sehilaaɓe"
lab var oral_reading_fluency_pr_37"37. ɓee"
lab var oral_reading_fluency_pr_38"38. pijii"
lab var oral_reading_fluency_pr_39"39. no"
lab var oral_reading_fluency_pr_40"40. moƴƴi."
lab var oral_reading_fluency_pr_41"41. Ɓe"
lab var oral_reading_fluency_pr_42"42. mbeltiima"
lab var oral_reading_fluency_pr_43"43. moƴƴa"

foreach g in oral_reading_fluency_stop_fr oral_reading_fluency_stop_wf oral_reading_fluency_stop_pr{
	lab var `g'"Interviewer: Was the stop rule triggered Oral reading fluency words?"
}
lab var reading_comprehension_fr_q1"Quel jour s'amusent-ils? [Samedi]"
lab var reading_comprehension_fr_q2"Où sont Ali et son petit frère ? [au tribunal; à l'école, etc]"
lab var reading_comprehension_fr_q3"Qu'est-ce que Sidi apporte avec lui ? [une balle]"
lab var reading_comprehension_fr_q4"Qui joue au ballon ? [Ali; Sidi; son frère; Ali et Sidi; etc.]"
lab var reading_comprehension_fr_q5"Comment sont les enfants à la fin du jeu? [heureux]"
lab var reading_comprehension_fr_q6"Pourquoi sont-ils heureux ? [ils ont bien joué, etc.]"

lab var reading_comprehension_wf_q1"Ban bés lañuy fo? [gaawu]"
lab var reading_comprehension_wf_q2"Fu Aali ak rakkam nekk ? [àttekaay ba; lekool ba, añs…..]"
lab var reading_comprehension_wf_q3"Lu Sidi indaale ? [ab bal]"
lab var reading_comprehension_wf_q4"Kuy fo ci bal bi? [Ali ; Sidi; rakkam; Aeli ak Sidi añs…...]"
lab var reading_comprehension_wf_q5"Nu xale yi mel bi po mi jeexee ? [bég]"
lab var reading_comprehension_wf_q6"Lu tax ñu bég ? [dañoo fo bu baax, añs…..]"

lab var reading_comprehension_sr_q1"Oxum bes a ŋasaayo ? [Gaaw]"
lab var reading_comprehension_sr_q2"Mam Aali fo ndeɓum a ndefu ? [ no maax ole ekol, flk ]"
lab var reading_comprehension_sr_q3"Xar Siidi a ɓislooxiidu ? [O bal]"
lab var reading_comprehension_sr_q4"Aniin naa ŋasaa fo bal ? [Aali; Siidi; o ndeɓum; Aali fa Siidi; flk.]"
lab var reading_comprehension_sr_q5"Nam xa caaƈ axe mbi'u ye faŋas fee a fagna ? [kaa da sawar/ kam den kaa ta ɓuuɓ]"
lab var reading_comprehension_sr_q6"Xar taxu kam no xa caaƈ axe ɓuuɓ  ? [Kaa da ŋas apaax, flk.]"

lab var reading_comprehension_pr_q1"Hol ñalawma ɓe pijata ? [Aset]"
lab var reading_comprehension_pr_q2"Hoto Aali e miñum gorko ngoni ? [to ñaawirdu, lekkol, ekn.]"
lab var reading_comprehension_pr_q3"Hol ko Siidi addori ? [bal]"
lab var reading_comprehension_pr_q4"Holi pettoowo bal ? [Aali ; Siidi ; miñum gorko ; Aali e Siidi ; ekn.]"
lab var reading_comprehension_pr_q5"Hol no sukaaɓe ɓee mbayi nde fijirde ndee gasi ? [mbeltiima]"
lab var reading_comprehension_pr_q6"Hol ko weltini ɓe ? [ɓe pijii no moƴƴi, ekn.]"

lab var rc_picture_matching_fr_q1"1. L'enfant joue."
lab var rc_picture_matching_fr_q10"10. Un groupe d'amis se réunit pour jouer le soir après l'école. Il y a toujours plus de deux enfants qui jouent. Ils chantent parfois des chansons, mais ils n'ont pas d'instruments. Ils n'ont pas non plus de ballon, alors ils jouent principalement à la marelle, à la corde à sauter ou à chat."
lab var rc_picture_matching_fr_q2"2. Il dort."
lab var rc_picture_matching_fr_q3"3. Chat et chien."
lab var rc_picture_matching_fr_q4"4. Le fermier laboure."
lab var rc_picture_matching_fr_q5"5. Le canard nage."
lab var rc_picture_matching_fr_q6"6. La souris est devant la boîte."
lab var rc_picture_matching_fr_q7"7. Les gens font de la musique."
lab var rc_picture_matching_fr_q8"8. Une poule couve ses œufs."
lab var rc_picture_matching_fr_q9"9. Dans mon village, il y a beaucoup de collines. J'aime jouer sur la colline où il y a un arbre isolé. C'est le meilleur pour l'escalade."

lab var rc_picture_matching_pr_q1"1. Cukalel na fija."
lab var rc_picture_matching_pr_q10"10. Goomu sehilaaɓe rentii ngam fijde caggal nde ɓe njippii lekkol. E kala sahaa ko ɓuri sukaaɓe ɗiɗo ina heen pija. Heen sahaaji ɓe ngona e yimde kono ɓe ngalaa pijirɗe. Ɓe ngalaa kadi bal, ɗuum saabii ɓe keewi fijirde tan ko tongoolongoƴel, diwo-diwongel, walla suuɗo-suuɗoondu."
lab var rc_picture_matching_pr_q2"2. Omo ɗaanoo."
lab var rc_picture_matching_pr_q3"3. Ullundu e rawaandu."
lab var rc_picture_matching_pr_q4"4. Jom ngesa na rema."
lab var rc_picture_matching_pr_q5"5. Kankaleewal na lummboo."
lab var rc_picture_matching_pr_q6"6. Doomru nduu nana yeeso boyet oo."
lab var rc_picture_matching_pr_q7"7. Yimɓe na piya bawɗi."
lab var rc_picture_matching_pr_q8"8. Gertognal na hippii e boofooɗe mum."
lab var rc_picture_matching_pr_q9"9. Nder wuro amen, na heewi tule. Miɗo yiɗi fijde e dow tulde ɗo waɗi lekki teelki. Ɗoon ɓuri welde e ŋabbugol."

lab var rc_picture_matching_sr_q1"1. O njaaƈ onqe oxe ŋasaa fo bal."
lab var rc_picture_matching_sr_q10"10. Gurup qaariit kaa mbokatoor ngir o ŋasik ekol o yaar yaa cang ale ƴutna.  A  jega kaa hupna xa caaƈ xa ƭaq akaa naa ŋasaa. Kaa ngimaa yoq ke, ndaa njegee pakir. Too njegee iitam o bal, na neene  da ŋasaa o fool no ƥaak mbaat muus ne."
lab var rc_picture_matching_sr_q2"2. O xe ɗaanaa."
lab var rc_picture_matching_sr_q3"3. Muus fo ɓox."
lab var rc_picture_matching_sr_q4"4. O qooxoox oxe xooxaa."
lab var rc_picture_matching_sr_q5"5. A kanaar ale oxe weƴaa."
lab var rc_picture_matching_sr_q6"6. Ƈoox ne o xe mbaamir kees ne."
lab var rc_picture_matching_sr_q7"7. Wiin we kaa mbakaa misik."
lab var rc_picture_matching_sr_q8"8. A cek a tew ale kaa ɓoofaa."
lab var rc_picture_matching_sr_q9"9. Kam saate'es, a jega loot mayu, kaam bug o ŋasaa took loot ne jegna ndaxar sengum. Ten moƴu o fel a ñootnax."

lab var rc_picture_matching_wf_q1"1. Xale baa ngi fo."
lab var rc_picture_matching_wf_q10"10. Mbooloom xarit a daje ngir fo ngoon si gannaaw bu ñu wàccee lekool. Am na saa su nekk lu ëpp ñaari xale yuy fo. Dañuy woy léeg-léeg, wànte amuñu ay jumtukaayi woy. Amuñu itam bal, looloo tax li ëpp seen po «palaning » la, « alambeer » walla powu muus."
lab var rc_picture_matching_wf_q2"2. Dafay nelaw."
lab var rc_picture_matching_wf_q3"3. Muus ak xaj."
lab var rc_picture_matching_wf_q4"4. Baykat baa ngi rijj."
lab var rc_picture_matching_wf_q5"5. kanaara (xànqel)  baa ngi féey."
lab var rc_picture_matching_wf_q6"6. Jinax jaa ngi ci kanamu boyet bi."
lab var rc_picture_matching_wf_q7"7. Nit ñaa ngi misik(tëgg)."
lab var rc_picture_matching_wf_q8"8. Genn ganaar a ngi bóof ay nenam."
lab var rc_picture_matching_wf_q9"9. Sama dëkk, am na ay tund yu bare. Dama bëgg di fo ci tund wi am ab garab gu beru. Fa la yéeg neexe."

foreach h in rc_pm_stop_fr rc_pm_stop_wf rc_pm_stop_pr{
	lab var `h'"Interviewer: Was the stop rule triggered Picture matching?"
}

foreach i in rc_picture_matching_example_fr rc_picture_matching_example_wf rc_picture_matching_example_pr{
	lab var `i'"The child runs"
}

lab var math_form_language"MATH SECTION"
lab var math_language_record"Enumerator: Select the language to be used for the mathematics section"
lab var  identifying_shapes_response_lang"Which language did the student respond in?"

foreach j in shapes_number_1 shapes_number_2 shapes_number_3{
	lab var `j'"Number of circled shapes"
}

lab var number_shapes_correct_1"The number of correctly circled triangles 1"
lab var number_shapes_correct_2"The number of correctly circled triangles 2"
lab var number_shapes_correct_3"The number of correctly circled triangles 3"

lab var position_tracking_response_langu"Which language did the student respond in?"

lab var position_tracking_1"Line 1: Further from the tree [Dog]"
lab var position_tracking_2"Line 2: Closer to the tree [Car]"
lab var position_tracking_3"Line 3: Closer to the tree [Ball]"
lab var position_tracking_4"Line 4: Further from the tree [Fish]"
lab var position_tracking_5"Line 5: Further from the tree [The red balloon]"
lab var position_tracking_6"Line 6: Closer to the tree [Bike]"
lab var identifying_numbers_response_lan"Which language did the student respond in?"
lab var identifying_numbers_grid_1_1"1. 6"
lab var identifying_numbers_grid_1_2"2. 8"
lab var identifying_numbers_grid_1_3"3. 4"
lab var identifying_numbers_grid_1_4"4. 2"
lab var identifying_numbers_grid_1_5"5. 1"
lab var identifying_numbers_grid_1_6"6. 9"
lab var identifying_numbers_grid_1_7"7. 7"
lab var identifying_numbers_grid_1_8"8. 10"

lab var identifying_numbers_grid_2_1"1. 12"
lab var identifying_numbers_grid_2_2"2. 14"
lab var identifying_numbers_grid_2_3"3. 19"
lab var identifying_numbers_grid_2_4"4. 20"
lab var identifying_numbers_grid_2_5"5. 21"
lab var identifying_numbers_grid_2_6"6. 33"
lab var identifying_numbers_grid_2_7"7. 27"
lab var identifying_numbers_grid_2_8"8. 38"

lab var identifying_numbers_grid_3_1"1. 44"
lab var identifying_numbers_grid_3_2"2. 45"
lab var identifying_numbers_grid_3_3"3. 29"
lab var identifying_numbers_grid_3_4"4. 50"

lab var counting_1"How many cars can you see here? [ 2 ]"
lab var counting_2"How many bulls do you see here? [ 5 ]"
lab var counting_3"How many pencils do you see here? [ 10 ]"
lab var counting_4"How many cars do you see here? [ 20 ]"
lab var counting_5"How many sheep do you see here? [ 30 ]"
lab var counting_6"How many peppers do you see here? [ 43 ]"
lab var counting_language"Which language did the student respond in?"
lab var digital_discrimination_language"Which language did the student respond in?"

lab var digital_discrimination_grid_1_1"a. 3"
lab var digital_discrimination_grid_1_2"b. 8"
lab var digital_discrimination_grid_1_3"c. 7"
lab var digital_discrimination_grid_1_4"d. 5"
lab var digital_discrimination_1num_corr"Number of items correct"
lab var digital_discrimination_grid_2_1"a. 15"
lab var digital_discrimination_grid_2_2"b. 20"
lab var digital_discrimination_grid_2_3"c. 41"
lab var digital_discrimination_grid_2_4"d. 37"
lab var digital_discrimination_2num_corr"Number of items correct"
lab var digital_discrimination_grid_3_1"a. 44 50"
lab var digital_discrimination_grid_3_2"b. 48 28"
lab var digital_discrimination_3num_corr"Number of items correct"

lab var missing_response_language"Which language did the student respond in?"
lab var missing_number_grid_1_1"a. 3"
lab var missing_number_grid_1_2"b. 10"
lab var missing_number_grid_1_3"c. 6"
lab var missing_number_grid_1_4"d. 20"
lab var missing_number_1num_corr"Number of items correct"

lab var missing_number_grid_2_1"a. 26"
lab var missing_number_grid_2_2"b. 27"
lab var missing_number_grid_2_3"c. 33"
lab var missing_number_grid_2_4"d. 47"
lab var missing_number_2num_corr"Number of items correct"

lab var decimal_response_language"Which language did the student respond in?"
lab var decimal_system_grid_1_1"a. 16"
lab var decimal_system_grid_1_2"b. 8"
lab var decimal_system_grid_1_3"c. 15"
lab var decimal_system_grid_1_4"d. 17"
lab var decimal_system_1num_corr"Number of items correct"

lab var decimal_system_grid_2_1"a. 10"
lab var decimal_system_grid_2_2"b. 13"
lab var decimal_system_grid_2_3"c. 36"
lab var decimal_system_grid_2_4"d. 46"
lab var decimal_system_2num_corr"Number of items correct"

lab var decimal_system_grid_3_1"a. 40"
lab var decimal_system_grid_3_2"b. 33"
lab var decimal_system_3num_corr"Number of items correct"

lab var addition_subtraction_1"1. 2 + 3 = [ 5 ]"
lab var addition_subtraction_2"2. 10 - 6 = [ 4 ]"
lab var addition_subtraction_3"3. 5 + 5 = [ 10 ]"
lab var addition_subtraction_4"4. 19 - 6 = [ 13 ]"
lab var addition_subtraction_5"5. 13 + 20 = [ 33 ]"

lab var addition_subtraction_strategy_1"Finger marks/ticks"
lab var addition_subtraction_strategy_2"Paper and pencil"
lab var addition_subtraction_strategy_3"Mental arithmetic"
lab var addition_subtraction_strategy_99"None of the above/did not respond"

ren addition_subtraction_response_la add_sub_response_language
ren word_addition_subtraction_respon word_add_sub_response_language
lab var word_add_sub_response_language"Which language did the student respond in?"

lab var word_addition_subtraction_1"1. 4-3 = [ 1 ]"
lab var word_addition_subtraction_2"2. 13+5 = [ 18 ]"
lab var word_addition_subtraction_3"3. 30 +15 = [ 45 ]"
lab var word_addition_subtraction_4"4. 37-24= [ 13 ]"
lab var word_addition_subtraction_5"5. 25+25 = [ 50 ]  OR  25 x 2 = [ 50 ]"

gen word_add_sub_strategy=""
order word_add_sub_strategy,before(word_add_sub_strategy_1)
lab var word_add_sub_strategy"Note the strategy the student used to solve the addition and subtraction question"
lab var word_add_sub_strategy_1"Finger marks/ticks"
lab var word_add_sub_strategy_2"Paper and pencil"
lab var word_add_sub_strategy_3"Mental arithmetic"
lab var word_add_sub_strategy_99"None of the above/did not respond"
lab var Comments"Field observations additional comments"
 
lab var GPSaccuracy"GPS Accuracy"
lab var GPSlatitude"GPS Latitude"
lab var GPSlongitude"GPS Longitude"