*IEF
lab define ief 1"IEF Nioro" 2"IEF Matam" 3"IEF Bambey" 4"IEF Kaolack dept"

replace selected_studentIEF_2_label = "1" if selected_studentIEF_2_label =="IEF Nioro"
replace selected_studentIEF_2_label = "2" if selected_studentIEF_2_label =="IEF Matam"
replace selected_studentIEF_2_label = "3" if selected_studentIEF_2_label =="IEF Bambey"
replace selected_studentIEF_2_label = "4" if selected_studentIEF_2_label =="IEF Kaolack dept"

destring selected_studentIEF_2_label, replace
ren selected_studentIEF_2_label IEF
lab values IEF ief

*Commune
lab define comm 1"Com Nioro" 2"Com Paoskoto" 3"Com Agnam Civol" 4"Com Matam" 5"Com Ogo" 6"Com Ndondol" 7"Com Ngogom" 8"Com Ngoye" 9"Com Refane" 10"Com Latmingué"

replace selected_studentCommune_2_label = "1" if selected_studentCommune_2_label =="Com Nioro"
replace selected_studentCommune_2_label = "2" if selected_studentCommune_2_label =="Com Paoskoto"
replace selected_studentCommune_2_label = "3" if selected_studentCommune_2_label =="Com Agnam Civol"
replace selected_studentCommune_2_label = "4" if selected_studentCommune_2_label =="Com Matam"
replace selected_studentCommune_2_label = "5" if selected_studentCommune_2_label =="Com Ogo"
replace selected_studentCommune_2_label = "6" if selected_studentCommune_2_label =="Com Ndondol"
replace selected_studentCommune_2_label = "7" if selected_studentCommune_2_label =="Com Ngogom"
replace selected_studentCommune_2_label = "8" if selected_studentCommune_2_label =="Com Ngoye" 
replace selected_studentCommune_2_label = "9" if selected_studentCommune_2_label =="Com Refane"
replace selected_studentCommune_2_label = "10" if selected_studentCommune_2_label =="Com Latmingué" | selected_studentCommune_2_label == "Com LatminguÃ©"

destring selected_studentCommune_2_label, replace
ren selected_studentCommune_2_label Commune
lab values Commune comm

**Ecole
lab define ecole 1"EE ABDOUL AZIZ SY" 2"EE INSA BOBO BA" 3"EE NIORO DAROU SALAM" 4"EE SAER MATY BA" 5"EE SARA THILOR BESSANE" 6"EE TIBOU NDOUR" 7"EFA NIORO COMMUNE" 8"EE DINGUIRAYE" 9"EE GAPAKH" 10"EE KEUR MALLE" 11"EE PAOSCOTO" 12"EE AGNAM CIVOL 1" 13"EE AGNAM GODO" 14"EE AGNAM GOLY 1" 15"EE AGNAM GOLY 2" 16"EE AGNAM LIDOUBE" 17"EE AGNAM THIODAYE 1" 18"EE AGNAM THIODAYE 2" 19"EE AGNAM TOULEL THIALE" 20"EE AGNAM WOURO CIRE" 21"EE NDIAFFANE SOROKOUM" 22"EE AMADOU BONGUEL NDIAYE" 23"EE APPLICATION IBRAHIMA SERIBA THIOUB" 24"EE DIAMEL 2" 25"EE EL HADJI BABA GUEYE" 26"EE HALWAR" 27"EE HAMEDINE BOCAR KANE" 28"EE YAYA ABDOULAYE DIAW" 29"EE BELLY NAYBE MBAYLA" 30"EE BELLY THIOYE" 31"EE DANTHIADY 1" 32"EE DIANDIOLY 2" 33"EE GALOYABE" 34"EE GANNA BALOL" 35"EE GARLY" 36"EE HOMBO" 37"EE OGO 1" 38"EE OGO 2" 39"EE SINTHIOU GARBA 1" 40"EE SINTHIOU GARBA 2" 41"EE SINTHIOU GARBA 3" 42"EE THIAMBE" 43"EE THIANCONE BOGUEL" 44"EE WASSACODE MBAILA" 45"EFA DANTHIADY" 46"EFA THIANCONE HIRAYE" 47"EE AK YAYE" 48"EE MBOMBOYE 2" 49"EE NDECK" 50"EE NDIEDIENG" 51"EE NDIEMANE" 52"EE NDONDOL EL HADJI GANA SENE" 53"EE NDONDOL WAKHALDIAM" 54"EE BAMBEY SERERE 1" 55"EE BAMBEY SERERE 3" 56"EE BAMBEY SERERE2" 57"EE CNRA" 58"EE KEUR ALIOU DIOUF" 59"EE KEUR MBAYE" 60"EE NDEME MEISSA" 61"EE NGOGOM" 62"EE NGUITHIE THIANDIGUE" 63"EE SILANE" 64"EFA BAMBEY SERERE" 65"EFA NGOTHIE" 66"EE BARRY NDONDOL" 67"EE BATTAL" 68"EE GOURGOURENE" 69"EE KEUR DAME" 70"EE KEUR MEISSA NDIAYE" 71"EE KHANDIAR NGOYE" 72"EE MBOKHODANE NGOYE" 73"EE NDIMB NGOYE" 74"EE NDIOULY1 NGOYE" 75"EE NGASCOP NGOYE" 76"EE NGOYE" 77"EE NGUEYE GUEYE NGOYE" 78"EE SOBEME SESSENE NGOYE" 79"EFA BATTAL" 80"EFA DAROU NDIOULY" 81"EE BOKH" 82"EE MBAMBEY" 83"EE NDEREPPE" 84"EE NDORONG MALICK" 85"EE NIANIAR" 86"EE REFANE 2" 87"EE REFANE" 88"EE REO MAO REFANE" 89"EFA NGOUYE THIANDIGUE" 90"EFA SASSAR" 91"PFA AL HAZAR REFANE" 92"EE DAGA YOUNDOUM" 93"EE KAWIL" 94"EE KOÏLAL" 95"EE LATMINGUE 1" 96"EE SAMBA NGOUILLE MAR" 97"EE SANGUIL" 98"EE SOUGOU NDIAYE" 99"EE THIAKHO MADIALE" 100"EFA HANENE"


replace selected_studentEcole_2_label = "1" if selected_studentEcole_2_label =="EE ABDOUL AZIZ SY"
replace selected_studentEcole_2_label = "2" if selected_studentEcole_2_label =="EE INSA BOBO BA"
replace selected_studentEcole_2_label = "3" if selected_studentEcole_2_label =="EE NIORO DAROU SALAM"
replace selected_studentEcole_2_label = "4" if selected_studentEcole_2_label =="EE SAER MATY BA"
replace selected_studentEcole_2_label = "5" if selected_studentEcole_2_label =="EE SARA THILOR BESSANE"
replace selected_studentEcole_2_label = "6" if selected_studentEcole_2_label =="EE TIBOU NDOUR"
replace selected_studentEcole_2_label = "7" if selected_studentEcole_2_label =="EFA NIORO COMMUNE"
replace selected_studentEcole_2_label = "8" if selected_studentEcole_2_label =="EE DINGUIRAYE"
replace selected_studentEcole_2_label = "9" if selected_studentEcole_2_label =="EE GAPAKH"
replace selected_studentEcole_2_label = "10" if selected_studentEcole_2_label =="EE KEUR MALLE"
replace selected_studentEcole_2_label = "11" if selected_studentEcole_2_label =="EE PAOSCOTO"
replace selected_studentEcole_2_label = "12" if selected_studentEcole_2_label =="EE AGNAM CIVOL 1"
replace selected_studentEcole_2_label = "13" if selected_studentEcole_2_label =="EE AGNAM GODO"
replace selected_studentEcole_2_label = "14" if selected_studentEcole_2_label =="EE AGNAM GOLY 1"
replace selected_studentEcole_2_label = "15" if selected_studentEcole_2_label =="EE AGNAM GOLY 2"
replace selected_studentEcole_2_label = "16" if selected_studentEcole_2_label =="EE AGNAM LIDOUBE"
replace selected_studentEcole_2_label = "17" if selected_studentEcole_2_label =="EE AGNAM THIODAYE 1"
replace selected_studentEcole_2_label = "18" if selected_studentEcole_2_label =="EE AGNAM THIODAYE 2"
replace selected_studentEcole_2_label = "19" if selected_studentEcole_2_label =="EE AGNAM TOULEL THIALE"
replace selected_studentEcole_2_label = "20" if selected_studentEcole_2_label =="EE AGNAM WOURO CIRE"
replace selected_studentEcole_2_label = "21" if selected_studentEcole_2_label =="EE NDIAFFANE SOROKOUM"
replace selected_studentEcole_2_label = "22" if selected_studentEcole_2_label =="EE AMADOU BONGUEL NDIAYE"
replace selected_studentEcole_2_label = "23" if selected_studentEcole_2_label =="EE APPLICATION IBRAHIMA SERIBA THIOUB"
replace selected_studentEcole_2_label = "24" if selected_studentEcole_2_label =="EE DIAMEL 2"
replace selected_studentEcole_2_label = "25" if selected_studentEcole_2_label =="EE EL HADJI BABA GUEYE"
replace selected_studentEcole_2_label = "26" if selected_studentEcole_2_label =="EE HALWAR"
replace selected_studentEcole_2_label = "27" if selected_studentEcole_2_label =="EE HAMEDINE BOCAR KANE"
replace selected_studentEcole_2_label = "28" if selected_studentEcole_2_label =="EE YAYA ABDOULAYE DIAW"
replace selected_studentEcole_2_label = "29" if selected_studentEcole_2_label =="EE BELLY NAYBE MBAYLA"
replace selected_studentEcole_2_label = "30" if selected_studentEcole_2_label =="EE BELLY THIOYE"
replace selected_studentEcole_2_label = "31" if selected_studentEcole_2_label =="EE DANTHIADY 1"
replace selected_studentEcole_2_label = "32" if selected_studentEcole_2_label =="EE DIANDIOLY 2"
replace selected_studentEcole_2_label = "33" if selected_studentEcole_2_label =="EE GALOYABE"
replace selected_studentEcole_2_label = "34" if selected_studentEcole_2_label =="EE GANNA BALOL"
replace selected_studentEcole_2_label = "35" if selected_studentEcole_2_label =="EE GARLY"
replace selected_studentEcole_2_label = "36" if selected_studentEcole_2_label =="EE HOMBO"
replace selected_studentEcole_2_label = "37" if selected_studentEcole_2_label =="EE OGO 1"
replace selected_studentEcole_2_label = "38" if selected_studentEcole_2_label =="EE OGO 2"
replace selected_studentEcole_2_label = "39" if selected_studentEcole_2_label =="EE SINTHIOU GARBA 1"
replace selected_studentEcole_2_label = "40" if selected_studentEcole_2_label =="EE SINTHIOU GARBA 2"
replace selected_studentEcole_2_label = "41" if selected_studentEcole_2_label =="EE SINTHIOU GARBA 3"
replace selected_studentEcole_2_label = "42" if selected_studentEcole_2_label =="EE THIAMBE"
replace selected_studentEcole_2_label = "43" if selected_studentEcole_2_label =="EE THIANCONE BOGUEL"
replace selected_studentEcole_2_label = "44" if selected_studentEcole_2_label =="EE WASSACODE MBAILA"
replace selected_studentEcole_2_label = "45" if selected_studentEcole_2_label =="EFA DANTHIADY"
replace selected_studentEcole_2_label = "46" if selected_studentEcole_2_label =="EFA THIANCONE HIRAYE"
replace selected_studentEcole_2_label = "47" if selected_studentEcole_2_label =="EE AK YAYE"
replace selected_studentEcole_2_label = "48" if selected_studentEcole_2_label =="EE MBOMBOYE 2"
replace selected_studentEcole_2_label = "49" if selected_studentEcole_2_label =="EE NDECK"
replace selected_studentEcole_2_label = "50" if selected_studentEcole_2_label =="EE NDIEDIENG"
replace selected_studentEcole_2_label = "51" if selected_studentEcole_2_label =="EE NDIEMANE"
replace selected_studentEcole_2_label = "52" if selected_studentEcole_2_label =="EE NDONDOL EL HADJI GANA SENE"
replace selected_studentEcole_2_label = "53" if selected_studentEcole_2_label =="EE NDONDOL WAKHALDIAM"
replace selected_studentEcole_2_label = "54" if selected_studentEcole_2_label =="EE BAMBEY SERERE 1"
replace selected_studentEcole_2_label = "55" if selected_studentEcole_2_label =="EE BAMBEY SERERE 3"
replace selected_studentEcole_2_label = "56" if selected_studentEcole_2_label =="EE BAMBEY SERERE2"
replace selected_studentEcole_2_label = "57" if selected_studentEcole_2_label =="EE CNRA"
replace selected_studentEcole_2_label = "58" if selected_studentEcole_2_label =="EE KEUR ALIOU DIOUF"
replace selected_studentEcole_2_label = "59" if selected_studentEcole_2_label =="EE KEUR MBAYE"
replace selected_studentEcole_2_label = "60" if selected_studentEcole_2_label =="EE NDEME MEISSA"
replace selected_studentEcole_2_label = "61" if selected_studentEcole_2_label =="EE NGOGOM"
replace selected_studentEcole_2_label = "62" if selected_studentEcole_2_label =="EE NGUITHIE THIANDIGUE"
replace selected_studentEcole_2_label = "63" if selected_studentEcole_2_label =="EE SILANE"
replace selected_studentEcole_2_label = "64" if selected_studentEcole_2_label =="EFA BAMBEY SERERE"
replace selected_studentEcole_2_label = "65" if selected_studentEcole_2_label =="EFA NGOTHIE"
replace selected_studentEcole_2_label = "66" if selected_studentEcole_2_label =="EE BARRY NDONDOL"
replace selected_studentEcole_2_label = "67" if selected_studentEcole_2_label =="EE BATTAL"
replace selected_studentEcole_2_label = "68" if selected_studentEcole_2_label =="EE GOURGOURENE"
replace selected_studentEcole_2_label = "69" if selected_studentEcole_2_label =="EE KEUR DAME"
replace selected_studentEcole_2_label = "70" if selected_studentEcole_2_label =="EE KEUR MEISSA NDIAYE"
replace selected_studentEcole_2_label = "71" if selected_studentEcole_2_label =="EE KHANDIAR NGOYE"
replace selected_studentEcole_2_label = "72" if selected_studentEcole_2_label =="EE MBOKHODANE NGOYE"
replace selected_studentEcole_2_label = "73" if selected_studentEcole_2_label =="EE NDIMB NGOYE"
replace selected_studentEcole_2_label = "74" if selected_studentEcole_2_label =="EE NDIOULY1 NGOYE"
replace selected_studentEcole_2_label = "75" if selected_studentEcole_2_label =="EE NGASCOP NGOYE"
replace selected_studentEcole_2_label = "76" if selected_studentEcole_2_label =="EE NGOYE"
replace selected_studentEcole_2_label = "77" if selected_studentEcole_2_label =="EE NGUEYE GUEYE NGOYE"
replace selected_studentEcole_2_label = "78" if selected_studentEcole_2_label =="EE SOBEME SESSENE NGOYE"
replace selected_studentEcole_2_label = "79" if selected_studentEcole_2_label =="EFA BATTAL"
replace selected_studentEcole_2_label = "80" if selected_studentEcole_2_label =="EFA DAROU NDIOULY"
replace selected_studentEcole_2_label = "81" if selected_studentEcole_2_label =="EE BOKH"
replace selected_studentEcole_2_label = "82" if selected_studentEcole_2_label =="EE MBAMBEY"
replace selected_studentEcole_2_label = "83" if selected_studentEcole_2_label =="EE NDEREPPE"
replace selected_studentEcole_2_label = "84" if selected_studentEcole_2_label =="EE NDORONG MALICK"
replace selected_studentEcole_2_label = "85" if selected_studentEcole_2_label =="EE NIANIAR"
replace selected_studentEcole_2_label = "86" if selected_studentEcole_2_label =="EE REFANE 2"
replace selected_studentEcole_2_label = "87" if selected_studentEcole_2_label =="EE REFANE"
replace selected_studentEcole_2_label = "88" if selected_studentEcole_2_label =="EE REO MAO REFANE"
replace selected_studentEcole_2_label = "89" if selected_studentEcole_2_label =="EFA NGOUYE THIANDIGUE"
replace selected_studentEcole_2_label = "90" if selected_studentEcole_2_label =="EFA SASSAR"
replace selected_studentEcole_2_label = "91" if selected_studentEcole_2_label =="PFA AL HAZAR REFANE"
replace selected_studentEcole_2_label = "92" if selected_studentEcole_2_label =="EE DAGA YOUNDOUM"
replace selected_studentEcole_2_label = "93" if selected_studentEcole_2_label =="EE KAWIL"
replace selected_studentEcole_2_label = "94" if selected_studentEcole_2_label =="EE KOÏLAL" | selected_studentEcole_2_label == "EE KOÃLAL"
replace selected_studentEcole_2_label = "95" if selected_studentEcole_2_label =="EE LATMINGUE 1"
replace selected_studentEcole_2_label = "96" if selected_studentEcole_2_label =="EE SAMBA NGOUILLE MAR"
replace selected_studentEcole_2_label = "97" if selected_studentEcole_2_label =="EE SANGUIL"
replace selected_studentEcole_2_label = "98" if selected_studentEcole_2_label =="EE SOUGOU NDIAYE"
replace selected_studentEcole_2_label = "99" if selected_studentEcole_2_label =="EE THIAKHO MADIALE"
replace selected_studentEcole_2_label = "100" if selected_studentEcole_2_label =="EFA HANENE"

destring selected_studentEcole_2_label, replace
ren selected_studentEcole_2_label Ecole
lab values Ecole ecole


*NIVEAU
lab define nive 2"CE1" 1"CP"

replace selected_studentNIVEAU_2_label= "2" if selected_studentNIVEAU_2_label =="CE1"
replace selected_studentNIVEAU_2_label= "1" if selected_studentNIVEAU_2_label =="CP"

destring selected_studentNIVEAU_2_label, replace
ren selected_studentNIVEAU_2_label Niveau
lab values Niveau nive


*Names/Classes
ren selected_studentEleve_nom_2_labe Eleve_nom 

ren selected_studentn_classes_2 n_classes

ren selected_studentCLASSE_NUM_2_lab CLASSE_NUM
destring CLASSE_NUM n_classes,replace

*Sexe
lab define sex 1"Fille" 2"Garçon"

replace selected_studentSexe_2_label= "1" if selected_studentSexe_2_label =="Fille"
replace selected_studentSexe_2_label= "2" if selected_studentSexe_2_label =="Garçon" | selected_studentSexe_2_label == "GarÃ§on"

destring selected_studentSexe_2_label, replace
ren selected_studentSexe_2_label Sexe
lab values Sexe sex

*
gen n_classes_2 = .
order n_classes_2,after(n_classes)
replace n_classes_2 =1 if n_classes == "J0LVakh0"
replace n_classes_2 =1 if n_classes == "omBlagc0"
replace n_classes_2 =1 if n_classes == "GUBd9dhR"
replace n_classes_2 =1 if n_classes == "esmjf62J"
replace n_classes_2 =1 if n_classes == "GT0YiXzO"
replace n_classes_2 =1 if n_classes == "MPrhSrYp"
replace n_classes_2 =1 if n_classes == "bBnMi8S1"
replace n_classes_2 =1 if n_classes == "33WFocaj"
replace n_classes_2 =1 if n_classes == "jgw4hXXL"
replace n_classes_2 =1 if n_classes == "B4H4J7CC"
replace n_classes_2 =1 if n_classes == "BpcPl0rO"
replace n_classes_2 =1 if n_classes == "lUYUmBQM"
replace n_classes_2 =2 if n_classes == "9obmQUnF"
replace n_classes_2 =2 if n_classes == "fRvgMsCd"
replace n_classes_2 =2 if n_classes == "jM2CoKvT"
replace n_classes_2 =2 if n_classes == "HpiUyNj2"
replace n_classes_2 =2 if n_classes == "8EwJPLf9"
replace n_classes_2 =2 if n_classes == "uJCGpSDf"
replace n_classes_2 =2 if n_classes == "GcDbjuZM"
replace n_classes_2 =2 if n_classes == "DnoXLIAr"
replace n_classes_2 =2 if n_classes == "NH2GDHjc"
replace n_classes_2 =2 if n_classes == "WbStoQ1M"
replace n_classes_2 =2 if n_classes == "tj3pDGse"
replace n_classes_2 =2 if n_classes == "ikLVE3Ci"
replace n_classes_2 =2 if n_classes == "6cttLQhI"
replace n_classes_2 =2 if n_classes == "KsIfCtFA"
replace n_classes_2 =2 if n_classes == "r58KyGc2"
replace n_classes_2 =2 if n_classes == "Eg0TFZXW"
replace n_classes_2 =2 if n_classes == "urbePTrH"
replace n_classes_2 =2 if n_classes == "S6KBBZji"
replace n_classes_2 =2 if n_classes == "tJkhLc20"
replace n_classes_2 =2 if n_classes == "FZhhugqF"
replace n_classes_2 =2 if n_classes == "OP9O2tBx"
replace n_classes_2 =2 if n_classes == "hf61BW3L"
replace n_classes_2 =2 if n_classes == "8sx67znJ"
replace n_classes_2 =2 if n_classes == "wGdJokfg"
replace n_classes_2 =2 if n_classes == "reMIbCMC"
replace n_classes_2 =2 if n_classes == "8sRrroq6"
replace n_classes_2 =2 if n_classes == "DFa2JtYJ"
replace n_classes_2 =2 if n_classes == "fNyrXets"
replace n_classes_2 =2 if n_classes == "zBfD2HH0"
replace n_classes_2 =2 if n_classes == "GdTqLwN8"
replace n_classes_2 =2 if n_classes == "5BrhvvKf"
replace n_classes_2 =2 if n_classes == "qoq5roa2"
replace n_classes_2 =2 if n_classes == "bLVriQkv"
replace n_classes_2 =2 if n_classes == "GVm2gDjb"
replace n_classes_2 =2 if n_classes == "q9emhnbi"
replace n_classes_2 =2 if n_classes == "ZD32ize9"
replace n_classes_2 =2 if n_classes == "iAYuQxZC"
replace n_classes_2 =2 if n_classes == "LIyYOOak"
replace n_classes_2 =2 if n_classes == "1YwsbpGh"
replace n_classes_2 =2 if n_classes == "oKh3cF2X"
replace n_classes_2 =2 if n_classes == "1U7TNwn4"
replace n_classes_2 =2 if n_classes == "lMPiLWfN"
replace n_classes_2 =2 if n_classes == "BCBIOOBZ"
replace n_classes_2 =2 if n_classes == "4C4zbWIk"
replace n_classes_2 =2 if n_classes == "sVnEIISP"
replace n_classes_2 =2 if n_classes == "euZzIUJA"
replace n_classes_2 =2 if n_classes == "n6wo0RrP"
replace n_classes_2 =2 if n_classes == "3EnID3nm"
replace n_classes_2 =2 if n_classes == "18EOzODU"
replace n_classes_2 =2 if n_classes == "Nr9ojGas"
replace n_classes_2 =2 if n_classes == "4MRAzcWT"
replace n_classes_2 =2 if n_classes == "0ApFpteA"
replace n_classes_2 =2 if n_classes == "5G5prrG3"
replace n_classes_2 =2 if n_classes == "fSOQzlOf"
replace n_classes_2 =2 if n_classes == "ecjNzxV2"
replace n_classes_2 =2 if n_classes == "N5HLfSlH"
replace n_classes_2 =2 if n_classes == "VkRbiMan"
replace n_classes_2 =2 if n_classes == "LtXTAADT"
replace n_classes_2 =2 if n_classes == "lFUGl8UP"
replace n_classes_2 =2 if n_classes == "VvpFF1GN"
replace n_classes_2 =2 if n_classes == "LirNzIRD"
replace n_classes_2 =2 if n_classes == "f5eSWsje"
replace n_classes_2 =2 if n_classes == "lODvw5WA"
replace n_classes_2 =2 if n_classes == "MmTtiXOr"
replace n_classes_2 =2 if n_classes == "6FgsAVtz"
replace n_classes_2 =2 if n_classes == "CxlQdWeW"
replace n_classes_2 =2 if n_classes == "4cks2w0N"
replace n_classes_2 =2 if n_classes == "9trl2QU3"
replace n_classes_2 =2 if n_classes == "3tYG2dhq"
replace n_classes_2 =2 if n_classes == "fcpRDee4"
replace n_classes_2 =2 if n_classes == "wy0wurf1"
replace n_classes_2 =2 if n_classes == "WuHxqM2g"
replace n_classes_2 =2 if n_classes == "Z4UpqGtG"
replace n_classes_2 =2 if n_classes == "a7cwXtEl"
replace n_classes_2 =2 if n_classes == "2CJf8Gcj"
replace n_classes_2 =2 if n_classes == "HJNG3QTi"
replace n_classes_2 =2 if n_classes == "cKwHf1lr"
replace n_classes_2 =2 if n_classes == "pcbPrf5f"
replace n_classes_2 =2 if n_classes == "8zTeozrw"
replace n_classes_2 =2 if n_classes == "llbP8eNl"
replace n_classes_2 =2 if n_classes == "zyqCtziQ"
replace n_classes_2 =2 if n_classes == "j00hKm9h"
replace n_classes_2 =2 if n_classes == "bRx6fdtG"
replace n_classes_2 =2 if n_classes == "auqM3MKQ"
replace n_classes_2 =1 if n_classes == "8dAQeUxK"
replace n_classes_2 =1 if n_classes == "8zlM7CWe"
replace n_classes_2 =1 if n_classes == "2BI0BDkZ"
replace n_classes_2 =1 if n_classes == "1goYHFXr"
replace n_classes_2 =1 if n_classes == "TypwV71s"
replace n_classes_2 =1 if n_classes == "NFOxGbIb"
replace n_classes_2 =1 if n_classes == "b0whBmzg"
replace n_classes_2 =1 if n_classes == "tufPqGNU"
replace n_classes_2 =1 if n_classes == "HHKj24xJ"
replace n_classes_2 =1 if n_classes == "ExlbKccG"
replace n_classes_2 =1 if n_classes == "mcWesMUA"
replace n_classes_2 =1 if n_classes == "dbf6Arb6"
replace n_classes_2 =1 if n_classes == "fckbcfpo"
replace n_classes_2 =1 if n_classes == "A2ffIMQk"
replace n_classes_2 =1 if n_classes == "I8wYyQ48"
replace n_classes_2 =1 if n_classes == "Qxa5oArA"
replace n_classes_2 =1 if n_classes == "ANW2Hw0D"
replace n_classes_2 =1 if n_classes == "pj38LEUS"
replace n_classes_2 =1 if n_classes == "Smne1DsR"
replace n_classes_2 =1 if n_classes == "bUEflmyB"
replace n_classes_2 =1 if n_classes == "U9JMd3tV"
replace n_classes_2 =1 if n_classes == "tJ5hOiFj"
replace n_classes_2 =1 if n_classes == "eYKygB7H"
replace n_classes_2 =1 if n_classes == "CjiqgKzb"
replace n_classes_2 =2 if n_classes == "lCR6eXO0"
replace n_classes_2 =2 if n_classes == "CrYMQOxa"
replace n_classes_2 =2 if n_classes == "qs7dlvSB"
replace n_classes_2 =2 if n_classes == "r5miEtoo"
replace n_classes_2 =2 if n_classes == "Z5iWeLjx"
replace n_classes_2 =2 if n_classes == "3dLRdYaJ"
replace n_classes_2 =2 if n_classes == "28kZUhFa"
replace n_classes_2 =2 if n_classes == "FHuM8f9t"
replace n_classes_2 =2 if n_classes == "Ja64QOK2"
replace n_classes_2 =2 if n_classes == "RFnJcNio"
replace n_classes_2 =2 if n_classes == "iT2DJUeN"
replace n_classes_2 =2 if n_classes == "A7GSfrmc"
replace n_classes_2 =1 if n_classes == "GsUlVLqp"
replace n_classes_2 =1 if n_classes == "wyZGGg2w"
replace n_classes_2 =1 if n_classes == "7DlvUDsb"
replace n_classes_2 =1 if n_classes == "catdVyXW"
replace n_classes_2 =1 if n_classes == "QS0yRQWt"
replace n_classes_2 =1 if n_classes == "sWF5WVew"
replace n_classes_2 =1 if n_classes == "6Nko7BdR"
replace n_classes_2 =1 if n_classes == "k2ort83b"
replace n_classes_2 =1 if n_classes == "yZzejmCO"
replace n_classes_2 =1 if n_classes == "47k2HYqo"
replace n_classes_2 =1 if n_classes == "dnOvCpMs"
replace n_classes_2 =1 if n_classes == "TFUuOaPK"
replace n_classes_2 =2 if n_classes == "ufO8QDtz"
replace n_classes_2 =2 if n_classes == "c00mlbdx"
replace n_classes_2 =2 if n_classes == "EG5DOZS5"
replace n_classes_2 =2 if n_classes == "kzQRKaV5"
replace n_classes_2 =2 if n_classes == "UT5mz3ov"
replace n_classes_2 =2 if n_classes == "PaEexekr"
replace n_classes_2 =2 if n_classes == "LokdKlM8"
replace n_classes_2 =2 if n_classes == "KVb9z0v6"
replace n_classes_2 =2 if n_classes == "8mC2bsQk"
replace n_classes_2 =2 if n_classes == "tGGQTe11"
replace n_classes_2 =2 if n_classes == "IVe583Bh"
replace n_classes_2 =2 if n_classes == "YexgEWDM"
replace n_classes_2 =2 if n_classes == "qXrjjuE4"
replace n_classes_2 =2 if n_classes == "4w6V8gYE"
replace n_classes_2 =2 if n_classes == "NCaGeLQF"
replace n_classes_2 =2 if n_classes == "Hjr1KqnX"
replace n_classes_2 =2 if n_classes == "0KGUUzSr"
replace n_classes_2 =2 if n_classes == "GaYXyy6b"
replace n_classes_2 =2 if n_classes == "VUmG6hDz"
replace n_classes_2 =2 if n_classes == "Oq2ghHoO"
replace n_classes_2 =2 if n_classes == "WkSXbRpv"
replace n_classes_2 =2 if n_classes == "Sw1YF1HR"
replace n_classes_2 =2 if n_classes == "8BvK2ycY"
replace n_classes_2 =2 if n_classes == "krO5x5HC"
replace n_classes_2 =1 if n_classes == "gnR6uAHL"
replace n_classes_2 =1 if n_classes == "yLyZ1VJV"
replace n_classes_2 =1 if n_classes == "sr0Wchms"
replace n_classes_2 =1 if n_classes == "7XWAM1fH"
replace n_classes_2 =1 if n_classes == "9pg4j2VP"
replace n_classes_2 =1 if n_classes == "6jQNmtE4"
replace n_classes_2 =1 if n_classes == "vBvTcAIj"
replace n_classes_2 =1 if n_classes == "YDsutnXC"
replace n_classes_2 =1 if n_classes == "zTH7mtY8"
replace n_classes_2 =1 if n_classes == "KlcM81RN"
replace n_classes_2 =1 if n_classes == "2R1dRlum"
replace n_classes_2 =1 if n_classes == "fdEG7YAu"
replace n_classes_2 =1 if n_classes == "lQ6mm5rf"
replace n_classes_2 =1 if n_classes == "XsEBxHZe"
replace n_classes_2 =1 if n_classes == "73dxAewP"
replace n_classes_2 =1 if n_classes == "4BjuDidY"
replace n_classes_2 =1 if n_classes == "E19p5WZy"
replace n_classes_2 =1 if n_classes == "iZldl1mM"
replace n_classes_2 =1 if n_classes == "iahaHJen"
replace n_classes_2 =1 if n_classes == "lpOlBvHp"
replace n_classes_2 =1 if n_classes == "FSFq3k2I"
replace n_classes_2 =1 if n_classes == "lsHjyYAP"
replace n_classes_2 =1 if n_classes == "5dnMkKDs"
replace n_classes_2 =1 if n_classes == "n5DQSSB0"
replace n_classes_2 =1 if n_classes == "ekY1jDWi"
replace n_classes_2 =1 if n_classes == "rssuOn3S"
replace n_classes_2 =1 if n_classes == "KCqGr4eN"
replace n_classes_2 =1 if n_classes == "kM6sh3Ip"
replace n_classes_2 =1 if n_classes == "o1sWbb3J"
replace n_classes_2 =1 if n_classes == "ZEjzutTO"
replace n_classes_2 =1 if n_classes == "H3nLKMEj"
replace n_classes_2 =1 if n_classes == "5YrM4Wpq"
replace n_classes_2 =1 if n_classes == "6DPk0huX"
replace n_classes_2 =1 if n_classes == "6pHa92DE"
replace n_classes_2 =1 if n_classes == "T6A5E0WM"
replace n_classes_2 =1 if n_classes == "GyMXINfP"
replace n_classes_2 =1 if n_classes == "bnIWPZK2"
replace n_classes_2 =1 if n_classes == "vUTXwFDH"
replace n_classes_2 =1 if n_classes == "64QTuvtm"
replace n_classes_2 =1 if n_classes == "U3zdPP43"
replace n_classes_2 =1 if n_classes == "lnQba7Nf"
replace n_classes_2 =1 if n_classes == "n8zkz3Qj"
replace n_classes_2 =1 if n_classes == "hFnldFmN"
replace n_classes_2 =1 if n_classes == "42aKBfeY"
replace n_classes_2 =1 if n_classes == "bE75a3IN"
replace n_classes_2 =1 if n_classes == "tylqrGxH"
replace n_classes_2 =1 if n_classes == "SRy8UWe4"
replace n_classes_2 =1 if n_classes == "geTgnxsk"
replace n_classes_2 =1 if n_classes == "jG0XxrS3"
replace n_classes_2 =1 if n_classes == "jmR15HTM"
replace n_classes_2 =1 if n_classes == "WiphfUd1"
replace n_classes_2 =1 if n_classes == "azFvQcdv"
replace n_classes_2 =1 if n_classes == "1HdTecXx"
replace n_classes_2 =1 if n_classes == "3VE9DI4v"
replace n_classes_2 =1 if n_classes == "5chaQb2c"
replace n_classes_2 =1 if n_classes == "cE6AxbiD"
replace n_classes_2 =1 if n_classes == "ngwI4oJw"
replace n_classes_2 =1 if n_classes == "EWEQE8o6"
replace n_classes_2 =1 if n_classes == "Cx8HsCsW"
replace n_classes_2 =1 if n_classes == "46cpoNTj"
replace n_classes_2 =1 if n_classes == "nsrfzWjr"
replace n_classes_2 =1 if n_classes == "Izw8dTLR"
replace n_classes_2 =1 if n_classes == "VbIXw0td"
replace n_classes_2 =1 if n_classes == "LSnmoK9V"
replace n_classes_2 =1 if n_classes == "hpbmGzFm"
replace n_classes_2 =1 if n_classes == "SBcDR8Sx"
replace n_classes_2 =1 if n_classes == "MffFcZcz"
replace n_classes_2 =1 if n_classes == "o7eyd5ue"
replace n_classes_2 =1 if n_classes == "skS2SNeY"
replace n_classes_2 =1 if n_classes == "TsF6UnIO"
replace n_classes_2 =1 if n_classes == "bKQdsnuP"
replace n_classes_2 =1 if n_classes == "qu5xavjA"
replace n_classes_2 =1 if n_classes == "iRFBhJ70"
replace n_classes_2 =1 if n_classes == "x3XaRx6Z"
replace n_classes_2 =1 if n_classes == "LDH3KuxF"
replace n_classes_2 =1 if n_classes == "qgPnGmnS"
replace n_classes_2 =1 if n_classes == "XOTVaRsw"
replace n_classes_2 =1 if n_classes == "b4aBhpad"
replace n_classes_2 =1 if n_classes == "Caar1ICL"
replace n_classes_2 =1 if n_classes == "Oz3fMxm4"
replace n_classes_2 =1 if n_classes == "CaQ2rCmY"
replace n_classes_2 =1 if n_classes == "3TSNkAmr"
replace n_classes_2 =1 if n_classes == "U6FsIIBH"
replace n_classes_2 =1 if n_classes == "Rev7l6ae"
replace n_classes_2 =2 if n_classes == "9QaEF130"
replace n_classes_2 =2 if n_classes == "ovdocqXW"
replace n_classes_2 =2 if n_classes == "VZBz5dqh"
replace n_classes_2 =2 if n_classes == "e5jDjvHG"
replace n_classes_2 =2 if n_classes == "CfsNkRGY"
replace n_classes_2 =2 if n_classes == "i4gWyCrt"
replace n_classes_2 =2 if n_classes == "vAQtYFVn"
replace n_classes_2 =2 if n_classes == "yICGMV2c"
replace n_classes_2 =2 if n_classes == "JYYDf9kQ"
replace n_classes_2 =2 if n_classes == "p401qL2x"
replace n_classes_2 =2 if n_classes == "bXITc4s9"
replace n_classes_2 =2 if n_classes == "l3wcGOCk"
replace n_classes_2 =2 if n_classes == "wQlsIzuK"
replace n_classes_2 =2 if n_classes == "tYt113zr"
replace n_classes_2 =2 if n_classes == "dERKHvF0"
replace n_classes_2 =2 if n_classes == "SJCnRQTH"
replace n_classes_2 =2 if n_classes == "n2edZQOd"
replace n_classes_2 =2 if n_classes == "ybt6MXON"
replace n_classes_2 =2 if n_classes == "HQNDyXDy"
replace n_classes_2 =2 if n_classes == "7bYmrTId"
replace n_classes_2 =2 if n_classes == "ZjWReEjZ"
replace n_classes_2 =2 if n_classes == "N074PN7p"
replace n_classes_2 =2 if n_classes == "j56bYug4"
replace n_classes_2 =2 if n_classes == "nFp6ftKR"
replace n_classes_2 =1 if n_classes == "Qf9Ceysv"
replace n_classes_2 =1 if n_classes == "W0LlT9Fm"
replace n_classes_2 =1 if n_classes == "RnhBDuuA"
replace n_classes_2 =1 if n_classes == "eFC2Ahr6"
replace n_classes_2 =1 if n_classes == "BdC2UeSQ"
replace n_classes_2 =1 if n_classes == "jVCZWkTC"
replace n_classes_2 =1 if n_classes == "yDgUwsoH"
replace n_classes_2 =1 if n_classes == "xzfXxmJB"
replace n_classes_2 =1 if n_classes == "AaE2w1HA"
replace n_classes_2 =1 if n_classes == "c7ycsJdI"
replace n_classes_2 =1 if n_classes == "8WW7xSI0"
replace n_classes_2 =2 if n_classes == "2vLdD2aE"
replace n_classes_2 =2 if n_classes == "V7g2LVnk"
replace n_classes_2 =2 if n_classes == "9G1dSmJY"
replace n_classes_2 =2 if n_classes == "ZpEZKjJr"
replace n_classes_2 =2 if n_classes == "w7mxcQie"
replace n_classes_2 =2 if n_classes == "fnHPkzK8"
replace n_classes_2 =2 if n_classes == "7Oljjoig"
replace n_classes_2 =2 if n_classes == "NQpK4oQJ"
replace n_classes_2 =2 if n_classes == "MlOCH26a"
replace n_classes_2 =2 if n_classes == "aWDUEc2E"
replace n_classes_2 =2 if n_classes == "CcZGd4im"
replace n_classes_2 =2 if n_classes == "xj6FfhhF"
replace n_classes_2 =2 if n_classes == "py6Cgpxp"
replace n_classes_2 =2 if n_classes == "OPqUsu76"
replace n_classes_2 =2 if n_classes == "YYIXembS"
replace n_classes_2 =2 if n_classes == "J5W69aCm"
replace n_classes_2 =2 if n_classes == "v6Wql1ns"
replace n_classes_2 =2 if n_classes == "2y9PxmbE"
replace n_classes_2 =2 if n_classes == "JXhjLMkB"
replace n_classes_2 =2 if n_classes == "PO7CuciE"
replace n_classes_2 =2 if n_classes == "82feSpwZ"
replace n_classes_2 =2 if n_classes == "h54tfxHr"
replace n_classes_2 =2 if n_classes == "26TQ2oLS"
replace n_classes_2 =2 if n_classes == "h0BmmQmL"
replace n_classes_2 =1 if n_classes == "dbpXUGwC"
replace n_classes_2 =1 if n_classes == "N4HcEs29"
replace n_classes_2 =1 if n_classes == "AaGS9NPo"
replace n_classes_2 =1 if n_classes == "HzkpvQYh"
replace n_classes_2 =1 if n_classes == "520HHrzv"
replace n_classes_2 =1 if n_classes == "GhapYwoM"
replace n_classes_2 =1 if n_classes == "Hc2rVnPr"
replace n_classes_2 =1 if n_classes == "1GSRyMVH"
replace n_classes_2 =1 if n_classes == "9B9S2rVc"
replace n_classes_2 =1 if n_classes == "QTZnkCXG"
replace n_classes_2 =1 if n_classes == "MUPQw4hj"
replace n_classes_2 =1 if n_classes == "eTa6vimW"
replace n_classes_2 =2 if n_classes == "pBBIsBhi"
replace n_classes_2 =2 if n_classes == "Us4ZUOGE"
replace n_classes_2 =2 if n_classes == "0tMeWziy"
replace n_classes_2 =2 if n_classes == "L8oPjZSJ"
replace n_classes_2 =2 if n_classes == "4K7qexpp"
replace n_classes_2 =2 if n_classes == "Ah56eL5J"
replace n_classes_2 =2 if n_classes == "wr2qevJw"
replace n_classes_2 =2 if n_classes == "LN0LsNwS"
replace n_classes_2 =2 if n_classes == "yRJHqy1W"
replace n_classes_2 =2 if n_classes == "mFWVCCR4"
replace n_classes_2 =2 if n_classes == "8s9WG4Tj"
replace n_classes_2 =2 if n_classes == "GALNxtze"
replace n_classes_2 =1 if n_classes == "fmMSHo9Z"
replace n_classes_2 =1 if n_classes == "uua1Aw4w"
replace n_classes_2 =1 if n_classes == "UwjS12mw"
replace n_classes_2 =1 if n_classes == "ZOAErARF"
replace n_classes_2 =1 if n_classes == "5OdMRVkP"
replace n_classes_2 =1 if n_classes == "qJpXIGUl"
replace n_classes_2 =1 if n_classes == "MeB4XPKn"
replace n_classes_2 =1 if n_classes == "Ct1cEihp"
replace n_classes_2 =1 if n_classes == "XOOaqG3A"
replace n_classes_2 =1 if n_classes == "YVW8zfSw"
replace n_classes_2 =1 if n_classes == "kZMPE9XL"
replace n_classes_2 =1 if n_classes == "rlJs2Cdy"
replace n_classes_2 =1 if n_classes == "Jv5PFfoB"
replace n_classes_2 =1 if n_classes == "crKtZeHV"
replace n_classes_2 =1 if n_classes == "OoO8lW0X"
replace n_classes_2 =1 if n_classes == "4w9K3Crx"
replace n_classes_2 =1 if n_classes == "BNPVy0tn"
replace n_classes_2 =1 if n_classes == "4H1G2Jpk"
replace n_classes_2 =1 if n_classes == "lRWXTQnT"
replace n_classes_2 =1 if n_classes == "iBd1RubP"
replace n_classes_2 =1 if n_classes == "jxbaodh4"
replace n_classes_2 =1 if n_classes == "kFDJLl8U"
replace n_classes_2 =1 if n_classes == "jva9SomS"
replace n_classes_2 =1 if n_classes == "cgg1xFhs"
replace n_classes_2 =1 if n_classes == "uXOBgczP"
replace n_classes_2 =1 if n_classes == "AzuxrSJ8"
replace n_classes_2 =1 if n_classes == "3agu3Bqg"
replace n_classes_2 =1 if n_classes == "tEMJj6VR"
replace n_classes_2 =1 if n_classes == "fcCVZjeW"
replace n_classes_2 =1 if n_classes == "ofBFL9LM"
replace n_classes_2 =1 if n_classes == "8GzcLXvh"
replace n_classes_2 =1 if n_classes == "1wcrNU5D"
replace n_classes_2 =1 if n_classes == "yMaOVjsA"
replace n_classes_2 =1 if n_classes == "JqWL2uUf"
replace n_classes_2 =1 if n_classes == "JMubHVyo"
replace n_classes_2 =1 if n_classes == "xnUvCPxA"
replace n_classes_2 =1 if n_classes == "iecJ478U"
replace n_classes_2 =1 if n_classes == "ffMzN8qP"
replace n_classes_2 =1 if n_classes == "UDOiLtBG"
replace n_classes_2 =1 if n_classes == "BTVLaz7R"
replace n_classes_2 =1 if n_classes == "C5iA4u9r"
replace n_classes_2 =1 if n_classes == "na2KDUmX"
replace n_classes_2 =1 if n_classes == "KGUQiaSm"
replace n_classes_2 =1 if n_classes == "Zx5TxQqd"
replace n_classes_2 =1 if n_classes == "SABJsetV"
replace n_classes_2 =1 if n_classes == "ArTwLXG0"
replace n_classes_2 =1 if n_classes == "dW4sjfyx"
replace n_classes_2 =1 if n_classes == "YUUp6VQo"
replace n_classes_2 =1 if n_classes == "U7ZbSDAR"
replace n_classes_2 =1 if n_classes == "JMnRQLjp"
replace n_classes_2 =1 if n_classes == "HGYBUjrX"
replace n_classes_2 =1 if n_classes == "hD1xmr16"
replace n_classes_2 =1 if n_classes == "rLWXRP9C"
replace n_classes_2 =1 if n_classes == "YsDLaQAQ"
replace n_classes_2 =1 if n_classes == "xXm0EL5A"
replace n_classes_2 =1 if n_classes == "9fOVYrlU"
replace n_classes_2 =1 if n_classes == "iyQqO8vD"
replace n_classes_2 =1 if n_classes == "X0VPmSFs"
replace n_classes_2 =1 if n_classes == "evloD4f7"
replace n_classes_2 =1 if n_classes == "RkhhYgSd"
replace n_classes_2 =1 if n_classes == "ycp3XSjM"
replace n_classes_2 =1 if n_classes == "uF6ePC7W"
replace n_classes_2 =1 if n_classes == "nMs506RT"
replace n_classes_2 =1 if n_classes == "kwmjlE6Z"
replace n_classes_2 =1 if n_classes == "BsPlkej2"
replace n_classes_2 =1 if n_classes == "oV3U3W3S"
replace n_classes_2 =1 if n_classes == "mgJo2g1A"
replace n_classes_2 =1 if n_classes == "WezMhurf"
replace n_classes_2 =1 if n_classes == "y4gAJ6xF"
replace n_classes_2 =1 if n_classes == "S6vsNrgy"
replace n_classes_2 =1 if n_classes == "ltjSXiLV"
replace n_classes_2 =1 if n_classes == "RQnZlF3i"
replace n_classes_2 =1 if n_classes == "Zh71uUAa"
replace n_classes_2 =1 if n_classes == "MpMYwcyx"
replace n_classes_2 =1 if n_classes == "YE7VrfbI"
replace n_classes_2 =1 if n_classes == "UF8NtxNS"
replace n_classes_2 =1 if n_classes == "3ig7cj4j"
replace n_classes_2 =1 if n_classes == "w1lykS29"
replace n_classes_2 =1 if n_classes == "rJHvLerx"
replace n_classes_2 =1 if n_classes == "XITnlfbO"
replace n_classes_2 =1 if n_classes == "WQNHyNyq"
replace n_classes_2 =1 if n_classes == "IICU0w7I"
replace n_classes_2 =1 if n_classes == "pKZ1ofkF"
replace n_classes_2 =1 if n_classes == "U4snygRN"
replace n_classes_2 =1 if n_classes == "oK90tpWK"
replace n_classes_2 =1 if n_classes == "zr8gQs59"
replace n_classes_2 =1 if n_classes == "aSEmDY9w"
replace n_classes_2 =1 if n_classes == "rmuUddbi"
replace n_classes_2 =1 if n_classes == "HlKENPnS"
replace n_classes_2 =1 if n_classes == "beSGy1GD"
replace n_classes_2 =1 if n_classes == "qacmi3iA"
replace n_classes_2 =1 if n_classes == "2IQShKdN"
replace n_classes_2 =1 if n_classes == "2sUhn3ud"
replace n_classes_2 =1 if n_classes == "jcij8KHg"
replace n_classes_2 =1 if n_classes == "lxDVoQSc"
replace n_classes_2 =1 if n_classes == "nndZD4p3"
replace n_classes_2 =1 if n_classes == "0K6j91vM"
replace n_classes_2 =1 if n_classes == "yUj2DhqE"
replace n_classes_2 =1 if n_classes == "YtBfVoNG"
replace n_classes_2 =1 if n_classes == "diFv2xq4"
replace n_classes_2 =1 if n_classes == "3wj3O26G"
replace n_classes_2 =1 if n_classes == "7U6PRe8h"
replace n_classes_2 =1 if n_classes == "lor5NZNp"
replace n_classes_2 =1 if n_classes == "TZvvc6T1"
replace n_classes_2 =1 if n_classes == "T6uVfccc"
replace n_classes_2 =1 if n_classes == "diZwdZy6"
replace n_classes_2 =1 if n_classes == "FWb4zg7K"
replace n_classes_2 =1 if n_classes == "Fl16o4oo"
replace n_classes_2 =1 if n_classes == "eoaRuXem"
replace n_classes_2 =1 if n_classes == "4Q3DAL6N"
replace n_classes_2 =1 if n_classes == "o4g0GsLC"
replace n_classes_2 =1 if n_classes == "De5s3po4"
replace n_classes_2 =1 if n_classes == "jUdNuFVG"
replace n_classes_2 =1 if n_classes == "vKh9ilmD"
replace n_classes_2 =1 if n_classes == "S70LXUBm"
replace n_classes_2 =1 if n_classes == "CueX5XbM"
replace n_classes_2 =1 if n_classes == "4QeLm2Fx"
replace n_classes_2 =1 if n_classes == "YQtxxKXs"
replace n_classes_2 =1 if n_classes == "5xev37bQ"
replace n_classes_2 =1 if n_classes == "mPwoxQOr"
replace n_classes_2 =2 if n_classes == "WfSoz9IY"
replace n_classes_2 =2 if n_classes == "cd59l1dL"
replace n_classes_2 =2 if n_classes == "VPQK5aWD"
replace n_classes_2 =2 if n_classes == "naEZVrKG"
replace n_classes_2 =2 if n_classes == "RHIZNOfN"
replace n_classes_2 =2 if n_classes == "pHQCFebe"
replace n_classes_2 =2 if n_classes == "EzPfBpmc"
replace n_classes_2 =2 if n_classes == "Q8nPKY8D"
replace n_classes_2 =2 if n_classes == "lvB8Dgmc"
replace n_classes_2 =2 if n_classes == "tIDBKZKq"
replace n_classes_2 =2 if n_classes == "3NVU0KA9"
replace n_classes_2 =2 if n_classes == "iw9szNg7"
replace n_classes_2 =1 if n_classes == "lyX8GMcP"
replace n_classes_2 =1 if n_classes == "gdgnJNnX"
replace n_classes_2 =1 if n_classes == "MCm1RtDs"
replace n_classes_2 =1 if n_classes == "I5KeAof4"
replace n_classes_2 =1 if n_classes == "nEmntdoB"
replace n_classes_2 =1 if n_classes == "0daaAa8a"
replace n_classes_2 =1 if n_classes == "GlwUV5wh"
replace n_classes_2 =1 if n_classes == "wA7h0i0f"
replace n_classes_2 =1 if n_classes == "Wapc8NaK"
replace n_classes_2 =1 if n_classes == "14UmMwvL"
replace n_classes_2 =1 if n_classes == "fVMPQ8N5"
replace n_classes_2 =1 if n_classes == "frvWB9C7"
replace n_classes_2 =1 if n_classes == "SqgYEoLq"
replace n_classes_2 =1 if n_classes == "D9wTRxpz"
replace n_classes_2 =1 if n_classes == "eYxYyTCi"
replace n_classes_2 =1 if n_classes == "fv9qUz7y"
replace n_classes_2 =1 if n_classes == "6VQlsn8E"
replace n_classes_2 =1 if n_classes == "qqFBA1Y8"
replace n_classes_2 =1 if n_classes == "jZHddfuZ"
replace n_classes_2 =1 if n_classes == "fGeUcDwO"
replace n_classes_2 =1 if n_classes == "Tg8QIE1Q"
replace n_classes_2 =1 if n_classes == "B4UIG0E1"
replace n_classes_2 =1 if n_classes == "xCNI9xA8"
replace n_classes_2 =1 if n_classes == "7GnDsshB"
replace n_classes_2 =2 if n_classes == "LZz2MHot"
replace n_classes_2 =2 if n_classes == "2Z3gOlwD"
replace n_classes_2 =2 if n_classes == "9CuOcHAL"
replace n_classes_2 =2 if n_classes == "EMz6g4cl"
replace n_classes_2 =2 if n_classes == "or9dHkV0"
replace n_classes_2 =2 if n_classes == "3kpBITAY"
replace n_classes_2 =2 if n_classes == "U4Elgn3v"
replace n_classes_2 =2 if n_classes == "5gENtXg1"
replace n_classes_2 =2 if n_classes == "dyknJx9n"
replace n_classes_2 =2 if n_classes == "zkoxZOzJ"
replace n_classes_2 =2 if n_classes == "P2KZWItu"
replace n_classes_2 =2 if n_classes == "lJ2dECmA"
replace n_classes_2 =1 if n_classes == "rvEZFXfd"
replace n_classes_2 =1 if n_classes == "ak5ax5rh"
replace n_classes_2 =1 if n_classes == "D5e0eXWC"
replace n_classes_2 =1 if n_classes == "1G5fhef2"
replace n_classes_2 =1 if n_classes == "23EhYC4t"
replace n_classes_2 =1 if n_classes == "smLQtT60"
replace n_classes_2 =1 if n_classes == "4h4b1Lhi"
replace n_classes_2 =1 if n_classes == "P9W3SOWG"
replace n_classes_2 =1 if n_classes == "3sO6ugC7"
replace n_classes_2 =1 if n_classes == "ROorOHvZ"
replace n_classes_2 =1 if n_classes == "CkcwxVO8"
replace n_classes_2 =1 if n_classes == "9fU1TcbN"
replace n_classes_2 =2 if n_classes == "AjCju0Hl"
replace n_classes_2 =2 if n_classes == "QEZkDtu8"
replace n_classes_2 =2 if n_classes == "tmuPJwkS"
replace n_classes_2 =2 if n_classes == "OGISgVCC"
replace n_classes_2 =2 if n_classes == "zDp8mxL2"
replace n_classes_2 =2 if n_classes == "90vsYmLI"
replace n_classes_2 =2 if n_classes == "2v0WjmAz"
replace n_classes_2 =2 if n_classes == "IEYqLm1J"
replace n_classes_2 =2 if n_classes == "iBfFnu87"
replace n_classes_2 =2 if n_classes == "IT5vY5W8"
replace n_classes_2 =2 if n_classes == "Lorh6Wfu"
replace n_classes_2 =2 if n_classes == "nR7dkG5O"
replace n_classes_2 =1 if n_classes == "i1t11OeB"
replace n_classes_2 =1 if n_classes == "jpw5TORL"
replace n_classes_2 =1 if n_classes == "DB6GTK0b"
replace n_classes_2 =1 if n_classes == "BUEnoaEo"
replace n_classes_2 =1 if n_classes == "RGN5hqPX"
replace n_classes_2 =1 if n_classes == "JMrU73uL"
replace n_classes_2 =1 if n_classes == "B2UneGwO"
replace n_classes_2 =1 if n_classes == "4scVlAIY"
replace n_classes_2 =1 if n_classes == "14BrK03i"
replace n_classes_2 =1 if n_classes == "uG1Rop1p"
replace n_classes_2 =1 if n_classes == "2hA5ocWc"
replace n_classes_2 =1 if n_classes == "Bf9oRoJ9"
replace n_classes_2 =2 if n_classes == "IowvzovU"
replace n_classes_2 =2 if n_classes == "KzTDmAIx"
replace n_classes_2 =2 if n_classes == "pjJI7SWg"
replace n_classes_2 =2 if n_classes == "j6D0veXI"
replace n_classes_2 =2 if n_classes == "j6XsJENS"
replace n_classes_2 =2 if n_classes == "qeJRfTnS"
replace n_classes_2 =2 if n_classes == "Ro62AJPL"
replace n_classes_2 =2 if n_classes == "Rb4aolaj"
replace n_classes_2 =2 if n_classes == "2j14kYA5"
replace n_classes_2 =2 if n_classes == "NJvtVwN0"
replace n_classes_2 =2 if n_classes == "yqh1ZGgV"
replace n_classes_2 =2 if n_classes == "UWjjSt5g"
replace n_classes_2 =1 if n_classes == "ikYVGcTH"
replace n_classes_2 =1 if n_classes == "QXG0jobI"
replace n_classes_2 =1 if n_classes == "hjQgNhm6"
replace n_classes_2 =1 if n_classes == "R7QeMWCs"
replace n_classes_2 =1 if n_classes == "FCZsANtm"
replace n_classes_2 =1 if n_classes == "6zhjT9RB"
replace n_classes_2 =1 if n_classes == "BoIdyDJq"
replace n_classes_2 =1 if n_classes == "0U0arQnq"
replace n_classes_2 =1 if n_classes == "vTx19y5b"
replace n_classes_2 =1 if n_classes == "caalDtou"
replace n_classes_2 =1 if n_classes == "0PyGmgdP"
replace n_classes_2 =1 if n_classes == "3Xz6YybY"
replace n_classes_2 =2 if n_classes == "kaSXVGZD"
replace n_classes_2 =2 if n_classes == "SduOpZUv"
replace n_classes_2 =2 if n_classes == "4hnMIwyR"
replace n_classes_2 =2 if n_classes == "d1sQgDUA"
replace n_classes_2 =2 if n_classes == "aCp94bh2"
replace n_classes_2 =2 if n_classes == "VXnPpICA"
replace n_classes_2 =2 if n_classes == "CORYujcQ"
replace n_classes_2 =2 if n_classes == "Tx8D96Xl"
replace n_classes_2 =2 if n_classes == "Oz25Zo1x"
replace n_classes_2 =2 if n_classes == "wL7SfvAt"
replace n_classes_2 =2 if n_classes == "uAxsTRRQ"
replace n_classes_2 =2 if n_classes == "KBEeufwI"
replace n_classes_2 =2 if n_classes == "DGtn1txe"
replace n_classes_2 =2 if n_classes == "JfrKtdXV"
replace n_classes_2 =2 if n_classes == "fgQb3Zy3"
replace n_classes_2 =2 if n_classes == "Oj9iDlS1"
replace n_classes_2 =2 if n_classes == "Oir0IlQd"
replace n_classes_2 =2 if n_classes == "0o7iyY32"
replace n_classes_2 =2 if n_classes == "mFT7zL0m"
replace n_classes_2 =2 if n_classes == "BQFEbkM7"
replace n_classes_2 =2 if n_classes == "WZy0044R"
replace n_classes_2 =2 if n_classes == "6hjzbPKl"
replace n_classes_2 =2 if n_classes == "0yYxNAaz"
replace n_classes_2 =2 if n_classes == "UU1eQOyZ"
replace n_classes_2 =2 if n_classes == "ZKVgHAEl"
replace n_classes_2 =2 if n_classes == "zVaCHD9k"
replace n_classes_2 =2 if n_classes == "Xz2WWkWM"
replace n_classes_2 =2 if n_classes == "e3txSjxg"
replace n_classes_2 =2 if n_classes == "W9ldENl1"
replace n_classes_2 =2 if n_classes == "NBjhwnGM"
replace n_classes_2 =2 if n_classes == "gWDkEXhU"
replace n_classes_2 =2 if n_classes == "RDoULKMX"
replace n_classes_2 =2 if n_classes == "91w5g7gZ"
replace n_classes_2 =2 if n_classes == "QTopmjLx"
replace n_classes_2 =2 if n_classes == "SQyAFypr"
replace n_classes_2 =2 if n_classes == "nSS1ODuG"
replace n_classes_2 =2 if n_classes == "GX9rR0a4"
replace n_classes_2 =2 if n_classes == "1lRtPIyf"
replace n_classes_2 =2 if n_classes == "4ZnepZOO"
replace n_classes_2 =2 if n_classes == "UHYOmblB"
replace n_classes_2 =2 if n_classes == "nbXGq941"
replace n_classes_2 =2 if n_classes == "SQDLBi8w"
replace n_classes_2 =2 if n_classes == "1JbI88bw"
replace n_classes_2 =2 if n_classes == "8rCzK7A9"
replace n_classes_2 =2 if n_classes == "OtWBn9RV"
replace n_classes_2 =2 if n_classes == "Sc0344Z8"
replace n_classes_2 =2 if n_classes == "pNbsAsTT"
replace n_classes_2 =2 if n_classes == "0CLRKnDg"
replace n_classes_2 =2 if n_classes == "lsUK757W"
replace n_classes_2 =2 if n_classes == "yt9NTLoS"
replace n_classes_2 =2 if n_classes == "MZA2fCTI"
replace n_classes_2 =2 if n_classes == "4Ex30Nqe"
replace n_classes_2 =2 if n_classes == "pFo1J973"
replace n_classes_2 =2 if n_classes == "nYJuWJ0r"
replace n_classes_2 =2 if n_classes == "nSMUBNOI"
replace n_classes_2 =2 if n_classes == "Bz1Dsodh"
replace n_classes_2 =2 if n_classes == "3iyTIvd7"
replace n_classes_2 =2 if n_classes == "xEbydbcd"
replace n_classes_2 =2 if n_classes == "7wYuyYM0"
replace n_classes_2 =2 if n_classes == "6zhSOdet"
replace n_classes_2 =1 if n_classes == "PdWUuVw3"
replace n_classes_2 =1 if n_classes == "5odlp0D9"
replace n_classes_2 =1 if n_classes == "SQm6L7jY"
replace n_classes_2 =1 if n_classes == "eGx07zcW"
replace n_classes_2 =1 if n_classes == "g45kTFp7"
replace n_classes_2 =1 if n_classes == "sU4MEHQy"
replace n_classes_2 =1 if n_classes == "q1LO52iI"
replace n_classes_2 =1 if n_classes == "jNRYO1ip"
replace n_classes_2 =1 if n_classes == "Y12IK5wu"
replace n_classes_2 =1 if n_classes == "lrIbclz5"
replace n_classes_2 =1 if n_classes == "vSKipACy"
replace n_classes_2 =1 if n_classes == "zYviOjfM"
replace n_classes_2 =2 if n_classes == "bMo8JXRA"
replace n_classes_2 =2 if n_classes == "PWOWC3hB"
replace n_classes_2 =2 if n_classes == "PJ1Jyaau"
replace n_classes_2 =2 if n_classes == "1MY6rAWC"
replace n_classes_2 =2 if n_classes == "FU9oXZFE"
replace n_classes_2 =2 if n_classes == "as2Aj47X"
replace n_classes_2 =2 if n_classes == "QdO2tag4"
replace n_classes_2 =2 if n_classes == "OKGmVOUL"
replace n_classes_2 =2 if n_classes == "xtE4ba2y"
replace n_classes_2 =2 if n_classes == "zGSCrLI2"
replace n_classes_2 =2 if n_classes == "nnJR5PId"
replace n_classes_2 =2 if n_classes == "gjHpbbQC"
replace n_classes_2 =2 if n_classes == "wor9MfiM"
replace n_classes_2 =2 if n_classes == "WlAfrPR4"
replace n_classes_2 =2 if n_classes == "AFLavSaw"
replace n_classes_2 =2 if n_classes == "PUkXvraL"
replace n_classes_2 =2 if n_classes == "IMVz6zPp"
replace n_classes_2 =2 if n_classes == "1Cd7xBTd"
replace n_classes_2 =2 if n_classes == "bMNZsBi9"
replace n_classes_2 =2 if n_classes == "0It5Lfze"
replace n_classes_2 =2 if n_classes == "ZMkecasB"
replace n_classes_2 =2 if n_classes == "VGompZ8N"
replace n_classes_2 =2 if n_classes == "36DvVEYY"
replace n_classes_2 =2 if n_classes == "4bCZPiic"
replace n_classes_2 =2 if n_classes == "l0FXgL5N"
replace n_classes_2 =2 if n_classes == "vwORze6A"
replace n_classes_2 =2 if n_classes == "Qlp6PbW3"
replace n_classes_2 =2 if n_classes == "hKGLwBjO"
replace n_classes_2 =2 if n_classes == "4mdJz8El"
replace n_classes_2 =2 if n_classes == "gqK8M4OH"
replace n_classes_2 =2 if n_classes == "aayDrLYe"
replace n_classes_2 =2 if n_classes == "6VPz10RD"
replace n_classes_2 =2 if n_classes == "Hv8LpdAZ"
replace n_classes_2 =2 if n_classes == "2nr8WbSZ"
replace n_classes_2 =2 if n_classes == "Vc1QhmHo"
replace n_classes_2 =2 if n_classes == "fKQZdVW4"
replace n_classes_2 =1 if n_classes == "zDbdrkf8"
replace n_classes_2 =1 if n_classes == "4rRlTLou"
replace n_classes_2 =1 if n_classes == "tJ9MGi6l"
replace n_classes_2 =1 if n_classes == "ZwmSwZgi"
replace n_classes_2 =1 if n_classes == "AEomvnxo"
replace n_classes_2 =1 if n_classes == "XsotmjqH"
replace n_classes_2 =1 if n_classes == "ICmpf3JK"
replace n_classes_2 =1 if n_classes == "4LROg0Rq"
replace n_classes_2 =1 if n_classes == "uvUs3vOs"
replace n_classes_2 =1 if n_classes == "OG0guwFl"
replace n_classes_2 =1 if n_classes == "FTt0LAjm"
replace n_classes_2 =1 if n_classes == "F09fHVfh"
replace n_classes_2 =1 if n_classes == "yUZ66eKJ"
replace n_classes_2 =1 if n_classes == "cJCfk7ZO"
replace n_classes_2 =1 if n_classes == "uhVNiESZ"
replace n_classes_2 =1 if n_classes == "SytPp74x"
replace n_classes_2 =1 if n_classes == "yyu7fBaO"
replace n_classes_2 =1 if n_classes == "RvYaWL77"
replace n_classes_2 =1 if n_classes == "HlBg4Lwa"
replace n_classes_2 =1 if n_classes == "BCubSqHp"
replace n_classes_2 =1 if n_classes == "cgYVTkTu"
replace n_classes_2 =1 if n_classes == "KjQ42AEe"
replace n_classes_2 =1 if n_classes == "srVGVINS"
replace n_classes_2 =1 if n_classes == "Y7HKzB2L"
replace n_classes_2 =1 if n_classes == "2GwHHyWR"
replace n_classes_2 =1 if n_classes == "TP8H9XGS"
replace n_classes_2 =1 if n_classes == "7hwWqtrH"
replace n_classes_2 =1 if n_classes == "tYwGqsRN"
replace n_classes_2 =1 if n_classes == "3LDZINfV"
replace n_classes_2 =1 if n_classes == "lv4gYi5O"
replace n_classes_2 =1 if n_classes == "3K0JbRUt"
replace n_classes_2 =1 if n_classes == "rHI1aknE"
replace n_classes_2 =1 if n_classes == "lrYG7TDW"
replace n_classes_2 =1 if n_classes == "b1fmvaib"
replace n_classes_2 =1 if n_classes == "vBgQIWlW"
replace n_classes_2 =1 if n_classes == "uHBzxwy1"
replace n_classes_2 =1 if n_classes == "SsZ6HXBC"
replace n_classes_2 =1 if n_classes == "a5TrFD8F"
replace n_classes_2 =1 if n_classes == "nzmrNRMA"
replace n_classes_2 =1 if n_classes == "JS0avoTZ"
replace n_classes_2 =1 if n_classes == "dOx9fAgT"
replace n_classes_2 =1 if n_classes == "iU4ZHmBf"
replace n_classes_2 =1 if n_classes == "qXvzMAMf"
replace n_classes_2 =1 if n_classes == "57KkdSbQ"
replace n_classes_2 =1 if n_classes == "f8VQ0u5J"
replace n_classes_2 =1 if n_classes == "USTBjsSs"
replace n_classes_2 =1 if n_classes == "bbvAEejo"
replace n_classes_2 =1 if n_classes == "8VSRcdg6"
replace n_classes_2 =2 if n_classes == "h3vfxNi4"
replace n_classes_2 =2 if n_classes == "q1ELlDTd"
replace n_classes_2 =2 if n_classes == "6jeWdyep"
replace n_classes_2 =2 if n_classes == "ZLhFwzop"
replace n_classes_2 =2 if n_classes == "xoiP8X18"
replace n_classes_2 =2 if n_classes == "prORjGqM"
replace n_classes_2 =2 if n_classes == "UqyQ1g9i"
replace n_classes_2 =2 if n_classes == "KMOWDlO3"
replace n_classes_2 =2 if n_classes == "0TRn9cA6"
replace n_classes_2 =2 if n_classes == "FszfP3ym"
replace n_classes_2 =2 if n_classes == "Ape8Gyr0"
replace n_classes_2 =2 if n_classes == "XJ5EYXAz"
replace n_classes_2 =1 if n_classes == "mORZDmrk"
replace n_classes_2 =1 if n_classes == "iHrMzqpu"
replace n_classes_2 =1 if n_classes == "7rhOymvP"
replace n_classes_2 =1 if n_classes == "1gxeLe0Y"
replace n_classes_2 =1 if n_classes == "XnBcWNQw"
replace n_classes_2 =1 if n_classes == "01iKzjq5"
replace n_classes_2 =1 if n_classes == "P5o8lMgF"
replace n_classes_2 =1 if n_classes == "4RmpxLhi"
replace n_classes_2 =1 if n_classes == "CqDUcLSp"
replace n_classes_2 =1 if n_classes == "kLay0neP"
replace n_classes_2 =1 if n_classes == "SKszo1Ov"
replace n_classes_2 =1 if n_classes == "1qewUV5F"
replace n_classes_2 =1 if n_classes == "MQDkJHZg"
replace n_classes_2 =1 if n_classes == "zsu8PiIg"
replace n_classes_2 =1 if n_classes == "QvOFrM80"
replace n_classes_2 =1 if n_classes == "4HN53CLj"
replace n_classes_2 =1 if n_classes == "jTu1r0nJ"
replace n_classes_2 =1 if n_classes == "U1Ppbegp"
replace n_classes_2 =1 if n_classes == "JEBR6JzA"
replace n_classes_2 =1 if n_classes == "QQ41GS8X"
replace n_classes_2 =1 if n_classes == "YVKo6MG0"
replace n_classes_2 =1 if n_classes == "pCP0deup"
replace n_classes_2 =1 if n_classes == "RZDqCKOu"
replace n_classes_2 =1 if n_classes == "O7gfaUik"
replace n_classes_2 =2 if n_classes == "SxXkDSxq"
replace n_classes_2 =2 if n_classes == "jM7j4oQQ"
replace n_classes_2 =2 if n_classes == "Lc7965ZK"
replace n_classes_2 =2 if n_classes == "r2zGn6nC"
replace n_classes_2 =2 if n_classes == "HGvKEHrv"
replace n_classes_2 =2 if n_classes == "wYErq2Yj"
replace n_classes_2 =2 if n_classes == "G4vE0Vdm"
replace n_classes_2 =2 if n_classes == "7BgpYxts"
replace n_classes_2 =2 if n_classes == "jzqaPkDq"
replace n_classes_2 =2 if n_classes == "tggteWWj"
replace n_classes_2 =2 if n_classes == "LeLX0MYj"
replace n_classes_2 =2 if n_classes == "SOEk9zai"
replace n_classes_2 =1 if n_classes == "NbCwlA5k"
replace n_classes_2 =1 if n_classes == "ruNVtjJM"
replace n_classes_2 =1 if n_classes == "UYTg7I75"
replace n_classes_2 =1 if n_classes == "NIYd0anL"
replace n_classes_2 =1 if n_classes == "8n5FOaMi"
replace n_classes_2 =1 if n_classes == "NDNqwrsm"
replace n_classes_2 =1 if n_classes == "nr27QJDG"
replace n_classes_2 =1 if n_classes == "rYLIrjhC"
replace n_classes_2 =1 if n_classes == "oSIJZhq3"
replace n_classes_2 =1 if n_classes == "QN9AIIDi"
replace n_classes_2 =1 if n_classes == "sEazf8Tj"
replace n_classes_2 =1 if n_classes == "KthphBik"
replace n_classes_2 =2 if n_classes == "aT4cZ4rN"
replace n_classes_2 =2 if n_classes == "avlgGp7f"
replace n_classes_2 =2 if n_classes == "442Fglpm"
replace n_classes_2 =2 if n_classes == "Ce2C9Isz"
replace n_classes_2 =2 if n_classes == "o6XicwAi"
replace n_classes_2 =2 if n_classes == "f5RsAVOk"
replace n_classes_2 =2 if n_classes == "pPOFyzmF"
replace n_classes_2 =2 if n_classes == "qJCrssT0"
replace n_classes_2 =2 if n_classes == "EYUc0v73"
replace n_classes_2 =2 if n_classes == "kdtrFOmy"
replace n_classes_2 =2 if n_classes == "VtfdipzK"
replace n_classes_2 =2 if n_classes == "eHzTSZ66"
replace n_classes_2 =2 if n_classes == "Kd3v0grg"
replace n_classes_2 =2 if n_classes == "8hbQK77h"
replace n_classes_2 =2 if n_classes == "z1exojEr"
replace n_classes_2 =2 if n_classes == "tVDbMLYM"
replace n_classes_2 =2 if n_classes == "wqQmiFyG"
replace n_classes_2 =2 if n_classes == "1C6gXrEc"
replace n_classes_2 =2 if n_classes == "I1PifELD"
replace n_classes_2 =2 if n_classes == "wGbULAh8"
replace n_classes_2 =2 if n_classes == "dhbRMnDN"
replace n_classes_2 =2 if n_classes == "Uz3nblEP"
replace n_classes_2 =2 if n_classes == "YeYAZsFT"
replace n_classes_2 =2 if n_classes == "veZvJGsJ"
replace n_classes_2 =1 if n_classes == "fLBPHyi1"
replace n_classes_2 =1 if n_classes == "w9xMwfpX"
replace n_classes_2 =1 if n_classes == "zHJdtdsp"
replace n_classes_2 =1 if n_classes == "nYom8vwN"
replace n_classes_2 =1 if n_classes == "3DCS2LIo"
replace n_classes_2 =1 if n_classes == "8eCkQ6Fh"
replace n_classes_2 =1 if n_classes == "Y71HpaLC"
replace n_classes_2 =1 if n_classes == "2ef8jo0h"
replace n_classes_2 =1 if n_classes == "NvqiyxvT"
replace n_classes_2 =1 if n_classes == "mTI9kSSw"
replace n_classes_2 =1 if n_classes == "I3uhZQoE"
replace n_classes_2 =1 if n_classes == "9UrvhHk6"
replace n_classes_2 =1 if n_classes == "thYyvMjT"
replace n_classes_2 =1 if n_classes == "2UB0jUaT"
replace n_classes_2 =1 if n_classes == "8iVeEIHi"
replace n_classes_2 =1 if n_classes == "CzT6H5Ri"
replace n_classes_2 =1 if n_classes == "LBDEzTpc"
replace n_classes_2 =1 if n_classes == "clIeTf2e"
replace n_classes_2 =1 if n_classes == "DL251mxo"
replace n_classes_2 =1 if n_classes == "yyefSVTg"
replace n_classes_2 =1 if n_classes == "RyUO8maK"
replace n_classes_2 =1 if n_classes == "RGD4KgMk"
replace n_classes_2 =1 if n_classes == "2TVluG0q"
replace n_classes_2 =1 if n_classes == "AaxKxtA1"
replace n_classes_2 =1 if n_classes == "YnYL6sca"
replace n_classes_2 =1 if n_classes == "zpN28yrf"
replace n_classes_2 =1 if n_classes == "AJu0tJzA"
replace n_classes_2 =1 if n_classes == "qdKdfneD"
replace n_classes_2 =1 if n_classes == "YAlRUvXL"
replace n_classes_2 =1 if n_classes == "tcynig5Q"
replace n_classes_2 =1 if n_classes == "P6kbynUi"
replace n_classes_2 =1 if n_classes == "VswZiT34"
replace n_classes_2 =1 if n_classes == "v2uLBUjl"
replace n_classes_2 =1 if n_classes == "s0yizaGS"
replace n_classes_2 =1 if n_classes == "nfEyjnLL"
replace n_classes_2 =1 if n_classes == "FXpzQqvd"
replace n_classes_2 =2 if n_classes == "ytgVNIWl"
replace n_classes_2 =2 if n_classes == "lmzFUkMj"
replace n_classes_2 =2 if n_classes == "YMIcnpOm"
replace n_classes_2 =2 if n_classes == "Mulx37jC"
replace n_classes_2 =2 if n_classes == "BRkmoOtk"
replace n_classes_2 =2 if n_classes == "JSmaHet0"
replace n_classes_2 =2 if n_classes == "u8A0vGVS"
replace n_classes_2 =2 if n_classes == "ndRd3ruT"
replace n_classes_2 =2 if n_classes == "8kgU8wOq"
replace n_classes_2 =2 if n_classes == "TzcQjMqG"
replace n_classes_2 =2 if n_classes == "PkIrV0Cq"
replace n_classes_2 =2 if n_classes == "q4nW0cwv"
replace n_classes_2 =2 if n_classes == "uilWi8IN"
replace n_classes_2 =2 if n_classes == "DKBBB6NI"
replace n_classes_2 =2 if n_classes == "MuBdafBs"
replace n_classes_2 =2 if n_classes == "FSvGiSir"
replace n_classes_2 =2 if n_classes == "0HmihJtX"
replace n_classes_2 =2 if n_classes == "f7oSpHob"
replace n_classes_2 =2 if n_classes == "UtBAsHbS"
replace n_classes_2 =2 if n_classes == "7RO4fvYA"
replace n_classes_2 =2 if n_classes == "2NGtQyJo"
replace n_classes_2 =2 if n_classes == "R1qYMdJb"
replace n_classes_2 =2 if n_classes == "4RcUvMvJ"
replace n_classes_2 =2 if n_classes == "Lb9AUip6"
replace n_classes_2 =1 if n_classes == "KSZI3kXW"
replace n_classes_2 =1 if n_classes == "cMUHa0bZ"
replace n_classes_2 =1 if n_classes == "bsFZH1Jv"
replace n_classes_2 =1 if n_classes == "0G4Pn2HT"
replace n_classes_2 =1 if n_classes == "tEcc4vtn"
replace n_classes_2 =1 if n_classes == "4vZvoU7c"
replace n_classes_2 =1 if n_classes == "LMyBLWVN"
replace n_classes_2 =1 if n_classes == "31lrG9he"
replace n_classes_2 =1 if n_classes == "DL8Zq5ko"
replace n_classes_2 =1 if n_classes == "Si0aTNg5"
replace n_classes_2 =1 if n_classes == "LRFzKuy2"
replace n_classes_2 =1 if n_classes == "Dezo9YGZ"
replace n_classes_2 =2 if n_classes == "VCow61Jg"
replace n_classes_2 =2 if n_classes == "Y0x1B7Bl"
replace n_classes_2 =2 if n_classes == "u8tCbphA"
replace n_classes_2 =2 if n_classes == "dmIZwHCy"
replace n_classes_2 =2 if n_classes == "CRzPrY1d"
replace n_classes_2 =2 if n_classes == "jk8Ge0lC"
replace n_classes_2 =2 if n_classes == "O1awYrm9"
replace n_classes_2 =2 if n_classes == "OykIfLaj"
replace n_classes_2 =2 if n_classes == "e56QeHlF"
replace n_classes_2 =2 if n_classes == "yEtiNVa2"
replace n_classes_2 =2 if n_classes == "8ECr4UCg"
replace n_classes_2 =2 if n_classes == "odjPPA7r"
replace n_classes_2 =2 if n_classes == "HnUyiR3y"
replace n_classes_2 =2 if n_classes == "qZrmXfL2"
replace n_classes_2 =2 if n_classes == "sAwdC0Oc"
replace n_classes_2 =2 if n_classes == "Tpsg6gZw"
replace n_classes_2 =2 if n_classes == "QVSAH6W0"
replace n_classes_2 =2 if n_classes == "toutoUCD"
replace n_classes_2 =2 if n_classes == "0HJw0HDi"
replace n_classes_2 =2 if n_classes == "YU8gRoZe"
replace n_classes_2 =2 if n_classes == "dc2ytjIK"
replace n_classes_2 =2 if n_classes == "IJJsYxBk"
replace n_classes_2 =2 if n_classes == "lXpEAABh"
replace n_classes_2 =2 if n_classes == "m7EbjWN0"
replace n_classes_2 =2 if n_classes == "vYSaBAT9"
replace n_classes_2 =2 if n_classes == "xu2J7CWX"
replace n_classes_2 =2 if n_classes == "oWEkV7H9"
replace n_classes_2 =2 if n_classes == "zJLnbwVU"
replace n_classes_2 =2 if n_classes == "iOvC8Ahl"
replace n_classes_2 =2 if n_classes == "Uqy35yeY"
replace n_classes_2 =2 if n_classes == "ir6X9pOH"
replace n_classes_2 =2 if n_classes == "KR3ayzIg"
replace n_classes_2 =2 if n_classes == "0RUQ5sBS"
replace n_classes_2 =2 if n_classes == "7CHW8Ftx"
replace n_classes_2 =2 if n_classes == "8O6YCNwZ"
replace n_classes_2 =2 if n_classes == "rHbFAYxw"
replace n_classes_2 =2 if n_classes == "gROVxPJH"
replace n_classes_2 =2 if n_classes == "jigr6zU8"
replace n_classes_2 =2 if n_classes == "lMiD6ccZ"
replace n_classes_2 =2 if n_classes == "gtVvo9m7"
replace n_classes_2 =2 if n_classes == "WQ3oxo36"
replace n_classes_2 =2 if n_classes == "QSiTQ2aY"
replace n_classes_2 =2 if n_classes == "rkPnT47D"
replace n_classes_2 =2 if n_classes == "vBkix1Ac"
replace n_classes_2 =2 if n_classes == "08PQKZbd"
replace n_classes_2 =2 if n_classes == "Nlp8Lpt2"
replace n_classes_2 =2 if n_classes == "PzCV70QM"
replace n_classes_2 =2 if n_classes == "553T38bO"
replace n_classes_2 =2 if n_classes == "Ozv8B4S4"
replace n_classes_2 =2 if n_classes == "i2kbi3RK"
replace n_classes_2 =2 if n_classes == "nFTC7qLN"
replace n_classes_2 =2 if n_classes == "BIIbCCDp"
replace n_classes_2 =2 if n_classes == "2BxxcWH4"
replace n_classes_2 =2 if n_classes == "h86q2I4M"
replace n_classes_2 =2 if n_classes == "3QXcEwVj"
replace n_classes_2 =2 if n_classes == "LcV5km4t"
replace n_classes_2 =2 if n_classes == "B8MmV7zC"
replace n_classes_2 =2 if n_classes == "oLTvd2Jt"
replace n_classes_2 =2 if n_classes == "k9nv126J"
replace n_classes_2 =2 if n_classes == "SHrHbY5A"
replace n_classes_2 =1 if n_classes == "6jMiNAFO"
replace n_classes_2 =1 if n_classes == "N6tOgpzT"
replace n_classes_2 =1 if n_classes == "Wlian46F"
replace n_classes_2 =1 if n_classes == "CChd0NLe"
replace n_classes_2 =1 if n_classes == "dnVQIlKH"
replace n_classes_2 =1 if n_classes == "7kqEFL7G"
replace n_classes_2 =1 if n_classes == "8CULc2bS"
replace n_classes_2 =1 if n_classes == "J3KNDFMd"
replace n_classes_2 =1 if n_classes == "WX0b9mqC"
replace n_classes_2 =1 if n_classes == "Ovr2iHNX"
replace n_classes_2 =1 if n_classes == "AsmojHnI"
replace n_classes_2 =1 if n_classes == "j64fUMh7"
replace n_classes_2 =2 if n_classes == "GQrQlzgn"
replace n_classes_2 =2 if n_classes == "u0md3Mob"
replace n_classes_2 =2 if n_classes == "yTpeDcvy"
replace n_classes_2 =2 if n_classes == "lDAWk0UW"
replace n_classes_2 =2 if n_classes == "J2rSrem0"
replace n_classes_2 =2 if n_classes == "3GpLPZO2"
replace n_classes_2 =2 if n_classes == "OcHjYP5v"
replace n_classes_2 =2 if n_classes == "SfFXhBwG"
replace n_classes_2 =2 if n_classes == "yD8AgRIJ"
replace n_classes_2 =2 if n_classes == "ajxUlaHP"
replace n_classes_2 =2 if n_classes == "jD69TEcJ"
replace n_classes_2 =2 if n_classes == "KD0iyshJ"
replace n_classes_2 =2 if n_classes == "LQenmC5N"
replace n_classes_2 =2 if n_classes == "QucSxmuH"
replace n_classes_2 =2 if n_classes == "oms8gLC4"
replace n_classes_2 =2 if n_classes == "5C5LUH5P"
replace n_classes_2 =2 if n_classes == "z0DXpzDL"
replace n_classes_2 =2 if n_classes == "Mpmo5N6m"
replace n_classes_2 =2 if n_classes == "alYupI7V"
replace n_classes_2 =2 if n_classes == "N4BPmi6z"
replace n_classes_2 =2 if n_classes == "jjaT2Rzz"
replace n_classes_2 =2 if n_classes == "L0rbFQjO"
replace n_classes_2 =2 if n_classes == "LI7AjCCP"
replace n_classes_2 =2 if n_classes == "soFEldrT"
replace n_classes_2 =2 if n_classes == "7YnaNtfV"
replace n_classes_2 =1 if n_classes == "kzBUV0zj"
replace n_classes_2 =1 if n_classes == "2c9COrMT"
replace n_classes_2 =1 if n_classes == "DbWOTVhY"
replace n_classes_2 =1 if n_classes == "xnSkoe2Y"
replace n_classes_2 =1 if n_classes == "eog1PfKB"
replace n_classes_2 =1 if n_classes == "SaVlpDfL"
replace n_classes_2 =1 if n_classes == "dNfKcoWo"
replace n_classes_2 =1 if n_classes == "EkNwsKQv"
replace n_classes_2 =1 if n_classes == "D8QXhDHu"
replace n_classes_2 =1 if n_classes == "JkpIsruJ"
replace n_classes_2 =1 if n_classes == "C5l8Z1B9"
replace n_classes_2 =1 if n_classes == "Di6iTWCM"
replace n_classes_2 =1 if n_classes == "Rr9N6qup"
replace n_classes_2 =1 if n_classes == "pxFjmrod"
replace n_classes_2 =1 if n_classes == "2GuJ7qu1"
replace n_classes_2 =1 if n_classes == "5gr4QwzI"
replace n_classes_2 =1 if n_classes == "vCJ1kL6A"
replace n_classes_2 =1 if n_classes == "TmbERSKB"
replace n_classes_2 =1 if n_classes == "64b1MPtn"
replace n_classes_2 =1 if n_classes == "MpqxWgvh"
replace n_classes_2 =1 if n_classes == "YUJGt71d"
replace n_classes_2 =1 if n_classes == "tMxdjGBg"
replace n_classes_2 =1 if n_classes == "r4Q9npb8"
replace n_classes_2 =1 if n_classes == "cSM7uIzD"
replace n_classes_2 =1 if n_classes == "e33N6vmG"
replace n_classes_2 =1 if n_classes == "Xi1gMDmf"
replace n_classes_2 =1 if n_classes == "uSlBCteo"
replace n_classes_2 =1 if n_classes == "zrPGSn8A"
replace n_classes_2 =1 if n_classes == "AQURV3Pe"
replace n_classes_2 =1 if n_classes == "kqKIcGqf"
replace n_classes_2 =1 if n_classes == "j9wB77Vq"
replace n_classes_2 =1 if n_classes == "CvJtL6pi"
replace n_classes_2 =1 if n_classes == "rHJfMvGZ"
replace n_classes_2 =1 if n_classes == "Id5B5qyg"
replace n_classes_2 =1 if n_classes == "ArKQOjuN"
replace n_classes_2 =1 if n_classes == "lILw3NQq"
replace n_classes_2 =1 if n_classes == "0K1M8yTm"
replace n_classes_2 =1 if n_classes == "5WtGInsY"
replace n_classes_2 =1 if n_classes == "IqbUg56j"
replace n_classes_2 =1 if n_classes == "tDFfW2JQ"
replace n_classes_2 =1 if n_classes == "CP6sa0zd"
replace n_classes_2 =1 if n_classes == "vzTKBKjZ"
replace n_classes_2 =1 if n_classes == "rm0JyaQq"
replace n_classes_2 =1 if n_classes == "6l0sdSJ7"
replace n_classes_2 =1 if n_classes == "pWlyIyk2"
replace n_classes_2 =1 if n_classes == "0QnHcYZS"
replace n_classes_2 =1 if n_classes == "1NrIDhqu"
replace n_classes_2 =1 if n_classes == "51Hqwbuo"
replace n_classes_2 =2 if n_classes == "YWtkIjW6"
replace n_classes_2 =2 if n_classes == "mDlStGhc"
replace n_classes_2 =2 if n_classes == "3qbLcYhB"
replace n_classes_2 =2 if n_classes == "PT83iXOp"
replace n_classes_2 =2 if n_classes == "e3h15Cqn"
replace n_classes_2 =2 if n_classes == "TklVHxcF"
replace n_classes_2 =2 if n_classes == "j3cWMQcm"
replace n_classes_2 =2 if n_classes == "HCdBsxvO"
replace n_classes_2 =2 if n_classes == "z6eKTBlx"
replace n_classes_2 =2 if n_classes == "MwMfQXga"
replace n_classes_2 =2 if n_classes == "0sNREkee"
replace n_classes_2 =2 if n_classes == "FF97gKYN"
replace n_classes_2 =1 if n_classes == "8qKMLrEz"
replace n_classes_2 =1 if n_classes == "pQ1PGusk"
replace n_classes_2 =1 if n_classes == "OctVAys2"
replace n_classes_2 =1 if n_classes == "NYUmXjzt"
replace n_classes_2 =1 if n_classes == "r7tQyRAf"
replace n_classes_2 =1 if n_classes == "FlRXotnM"
replace n_classes_2 =1 if n_classes == "B14CrZ1Z"
replace n_classes_2 =1 if n_classes == "PBWTvVv2"
replace n_classes_2 =1 if n_classes == "ShH6Um2I"
replace n_classes_2 =1 if n_classes == "MXr8mv0T"
replace n_classes_2 =1 if n_classes == "FfObi2sx"
replace n_classes_2 =1 if n_classes == "Cct4W4BP"
replace n_classes_2 =2 if n_classes == "hNSOVm0A"
replace n_classes_2 =2 if n_classes == "fPIpTE74"
replace n_classes_2 =2 if n_classes == "aFJVB7q3"
replace n_classes_2 =2 if n_classes == "H4n66Pq0"
replace n_classes_2 =2 if n_classes == "45KKSu7J"
replace n_classes_2 =2 if n_classes == "HN13UU9y"
replace n_classes_2 =2 if n_classes == "XwS6ws5t"
replace n_classes_2 =2 if n_classes == "U6P6ywV2"
replace n_classes_2 =2 if n_classes == "4VN9tNs0"
replace n_classes_2 =2 if n_classes == "vRGHAEJy"
replace n_classes_2 =2 if n_classes == "zTXmfoDR"
replace n_classes_2 =2 if n_classes == "XrImqK3Z"
replace n_classes_2 =1 if n_classes == "rMmDcT52"
replace n_classes_2 =1 if n_classes == "LMEEcaEr"
replace n_classes_2 =1 if n_classes == "rDfotkeN"
replace n_classes_2 =1 if n_classes == "XJWEtjJC"
replace n_classes_2 =1 if n_classes == "8S2ku10r"
replace n_classes_2 =1 if n_classes == "JMKxeBZI"
replace n_classes_2 =1 if n_classes == "8jTwQHDd"
replace n_classes_2 =1 if n_classes == "P9oIsEot"
replace n_classes_2 =1 if n_classes == "56VWMbLG"
replace n_classes_2 =1 if n_classes == "6sDPIgeJ"
replace n_classes_2 =1 if n_classes == "pucdlVWu"
replace n_classes_2 =1 if n_classes == "ZI0134Ei"
replace n_classes_2 =1 if n_classes == "47pivYBH"
replace n_classes_2 =1 if n_classes == "fdXVa1rO"
replace n_classes_2 =1 if n_classes == "h9lJKW0h"
replace n_classes_2 =1 if n_classes == "YdmENw3c"
replace n_classes_2 =1 if n_classes == "AjBCyCkp"
replace n_classes_2 =1 if n_classes == "dKpk0UmW"
replace n_classes_2 =1 if n_classes == "i2fMVd49"
replace n_classes_2 =1 if n_classes == "V7VTTPid"
replace n_classes_2 =1 if n_classes == "AO6wCbuO"
replace n_classes_2 =1 if n_classes == "r7rMbVnf"
replace n_classes_2 =1 if n_classes == "fCcF3cz1"
replace n_classes_2 =1 if n_classes == "in0d5Ddb"
replace n_classes_2 =1 if n_classes == "fyj8z810"
replace n_classes_2 =1 if n_classes == "NzTn6oq4"
replace n_classes_2 =1 if n_classes == "eVbfl2F2"
replace n_classes_2 =1 if n_classes == "uQFL7Rjn"
replace n_classes_2 =1 if n_classes == "GG5gijcD"
replace n_classes_2 =1 if n_classes == "eSlf3neP"
replace n_classes_2 =1 if n_classes == "z25XzVtY"
replace n_classes_2 =1 if n_classes == "XHn1iQsw"
replace n_classes_2 =1 if n_classes == "OZOqWpgF"
replace n_classes_2 =1 if n_classes == "3DjQzCP5"
replace n_classes_2 =1 if n_classes == "i2qY0fUQ"
replace n_classes_2 =1 if n_classes == "frsFrXeQ"
replace n_classes_2 =1 if n_classes == "7GUToZ4B"
replace n_classes_2 =1 if n_classes == "8P9IIYML"
replace n_classes_2 =1 if n_classes == "4acHkyao"
replace n_classes_2 =1 if n_classes == "RqhAPWHy"
replace n_classes_2 =1 if n_classes == "D2t50PYw"
replace n_classes_2 =1 if n_classes == "Rq2TMUXb"
replace n_classes_2 =1 if n_classes == "BY85hXal"
replace n_classes_2 =1 if n_classes == "WoaQjAMQ"
replace n_classes_2 =1 if n_classes == "f9XagbhW"
replace n_classes_2 =1 if n_classes == "BG0JPm7k"
replace n_classes_2 =1 if n_classes == "GrtHY1SY"
replace n_classes_2 =1 if n_classes == "PM9vBjMe"
replace n_classes_2 =1 if n_classes == "P9xPzROO"
replace n_classes_2 =1 if n_classes == "LjSrP8jk"
replace n_classes_2 =1 if n_classes == "KG7mvpsN"
replace n_classes_2 =1 if n_classes == "IM1vIhSn"
replace n_classes_2 =1 if n_classes == "Mm5fxQhO"
replace n_classes_2 =1 if n_classes == "QwSQnkyn"
replace n_classes_2 =1 if n_classes == "qmdkfuss"
replace n_classes_2 =1 if n_classes == "zK5SARS2"
replace n_classes_2 =1 if n_classes == "Q8HQRgL8"
replace n_classes_2 =1 if n_classes == "YzTfsaCa"
replace n_classes_2 =1 if n_classes == "CSzaZzQ6"
replace n_classes_2 =1 if n_classes == "2tk8UCIy"
replace n_classes_2 =1 if n_classes == "QUZTwzzZ"
replace n_classes_2 =1 if n_classes == "e2TTwBE9"
replace n_classes_2 =1 if n_classes == "3JKaAm06"
replace n_classes_2 =1 if n_classes == "J8Sbwfl3"
replace n_classes_2 =1 if n_classes == "d0EGfHP0"
replace n_classes_2 =1 if n_classes == "5NvwTCNg"
replace n_classes_2 =1 if n_classes == "1vPiqLN1"
replace n_classes_2 =1 if n_classes == "Ujb5om9F"
replace n_classes_2 =1 if n_classes == "VXxnh0SY"
replace n_classes_2 =1 if n_classes == "t3uJHNbL"
replace n_classes_2 =1 if n_classes == "upURACsp"
replace n_classes_2 =1 if n_classes == "FAxKJG4p"
replace n_classes_2 =2 if n_classes == "jc9IJEi5"
replace n_classes_2 =2 if n_classes == "kNnIy1xw"
replace n_classes_2 =2 if n_classes == "KC1zJqK7"
replace n_classes_2 =2 if n_classes == "9ZX1Y8Ya"
replace n_classes_2 =2 if n_classes == "dpNJ3H7O"
replace n_classes_2 =2 if n_classes == "ycUfAw94"
replace n_classes_2 =2 if n_classes == "6cQiRjyN"
replace n_classes_2 =2 if n_classes == "zgzjC256"
replace n_classes_2 =2 if n_classes == "W8mwU5OY"
replace n_classes_2 =2 if n_classes == "afqYYZwa"
replace n_classes_2 =2 if n_classes == "tOdmnvUj"
replace n_classes_2 =2 if n_classes == "mAcwNcZY"
replace n_classes_2 =1 if n_classes == "BSEcmOUm"
replace n_classes_2 =1 if n_classes == "yky6vJ4Z"
replace n_classes_2 =1 if n_classes == "nsXGDyM0"
replace n_classes_2 =1 if n_classes == "37Yoc6nw"
replace n_classes_2 =1 if n_classes == "UmEIsZ1Q"
replace n_classes_2 =1 if n_classes == "SBzvEaXb"
replace n_classes_2 =1 if n_classes == "hSefsTui"
replace n_classes_2 =1 if n_classes == "SQ7X2RQe"
replace n_classes_2 =1 if n_classes == "EHJDM0VP"
replace n_classes_2 =1 if n_classes == "u57oJhyL"
replace n_classes_2 =1 if n_classes == "FBxktjxf"
replace n_classes_2 =1 if n_classes == "44QZQN2n"
replace n_classes_2 =1 if n_classes == "89CebBy9"
replace n_classes_2 =1 if n_classes == "fmiaMF7f"
replace n_classes_2 =1 if n_classes == "ICgp9Ioo"
replace n_classes_2 =1 if n_classes == "kC7h8aeD"
replace n_classes_2 =1 if n_classes == "JhFFC60l"
replace n_classes_2 =1 if n_classes == "QWs1xVN1"
replace n_classes_2 =1 if n_classes == "k5v9A6Uu"
replace n_classes_2 =1 if n_classes == "XNpKA8Gg"
replace n_classes_2 =1 if n_classes == "JZ8vLcgX"
replace n_classes_2 =1 if n_classes == "NIHQtGLB"
replace n_classes_2 =1 if n_classes == "HUUYWOcv"
replace n_classes_2 =1 if n_classes == "YdkZsX3L"
replace n_classes_2 =2 if n_classes == "5n6Ed60E"
replace n_classes_2 =2 if n_classes == "juPY4eGm"
replace n_classes_2 =2 if n_classes == "owU125Es"
replace n_classes_2 =2 if n_classes == "gaXritBg"
replace n_classes_2 =2 if n_classes == "cxGQJLIJ"
replace n_classes_2 =2 if n_classes == "6w735GQT"
replace n_classes_2 =2 if n_classes == "L2Wcy6xX"
replace n_classes_2 =2 if n_classes == "27dRYU6s"
replace n_classes_2 =2 if n_classes == "6O3cp7YR"
replace n_classes_2 =2 if n_classes == "GVpr54aD"
replace n_classes_2 =2 if n_classes == "rM9CeM39"
replace n_classes_2 =1 if n_classes == "guLsnkEE"
replace n_classes_2 =1 if n_classes == "Ga9degKD"
replace n_classes_2 =1 if n_classes == "fikgLnhM"
replace n_classes_2 =1 if n_classes == "dIC44qq1"
replace n_classes_2 =1 if n_classes == "u0ED3gVN"
replace n_classes_2 =1 if n_classes == "MPrz1oe2"
replace n_classes_2 =1 if n_classes == "lVSqJyPS"
replace n_classes_2 =1 if n_classes == "F3ATYgRn"
replace n_classes_2 =1 if n_classes == "GtCmDbRU"
replace n_classes_2 =1 if n_classes == "6RQ9wtc9"
replace n_classes_2 =1 if n_classes == "P4PkAlS2"
replace n_classes_2 =1 if n_classes == "irMDsQh1"
replace n_classes_2 =2 if n_classes == "6kg4JAQP"
replace n_classes_2 =2 if n_classes == "CrmDECjT"
replace n_classes_2 =2 if n_classes == "XxkjRCGM"
replace n_classes_2 =2 if n_classes == "Q3xml7UR"
replace n_classes_2 =2 if n_classes == "2Tiulh89"
replace n_classes_2 =2 if n_classes == "mj4H4ucV"
replace n_classes_2 =2 if n_classes == "Fy2CLAKw"
replace n_classes_2 =2 if n_classes == "rDArW2Zh"
replace n_classes_2 =2 if n_classes == "x22l5115"
replace n_classes_2 =2 if n_classes == "izzTSavY"
replace n_classes_2 =2 if n_classes == "qUYEWHyG"
replace n_classes_2 =2 if n_classes == "TxDwpIoS"












